/* TA20 actual deployed page and independently projected source geometry.
 * Never starts a server. Interactive invocation requires explicit public HTTPS.
 * Separately authorized CI may use its own loopback runner; this task never does.
 */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),net=require('node:net'),{chromium}=require('playwright');
function allowed(value){const u=new URL(value),h=u.hostname.toLowerCase().replace(/\.$/,'');if(process.env.CI==='true'&&u.protocol==='http:'&&h==='127.0.0.1'&&u.port)return u;assert.equal(u.protocol,'https:');assert.ok(!u.username&&!u.password&&!net.isIP(h));assert.ok(h.includes('.')&&!/(^|\.)(localhost|local|internal|localdomain|test|invalid)$/.test(h));assert.ok(!/(^|\.)(nip\.io|sslip\.io|localtest\.me|lvh\.me)$/.test(h));assert.ok(!u.port||u.port==='443');return u}
assert.ok(process.env.UI_BASE_URL,'Explicit public origin required; no local fallback');const origin=allowed(process.env.UI_BASE_URL);assert.equal(origin.pathname,'/');assert.ok(!origin.search&&!origin.hash);const base=origin.origin;
const root=process.env.TA20_SOURCE_ROOT||path.resolve(__dirname,'..'),out=process.env.REVIEW_SCREENSHOTS||'/private/tmp/ta20-public-'+Date.now(),D=path.join(root,'docs/design/technical-atlas/TA-20');fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),proof=JSON.parse(fs.readFileSync(path.join(D,'native-render-proof-v2.json'))),labels=JSON.parse(fs.readFileSync(path.join(D,'labels-v1.json')));
const results={observed_at:new Date().toISOString(),base,views:[],downloads:[],sources:[],errors:[],route_errors:[]};let browser;
(async()=>{try{browser=await chromium.launch({headless:process.env.UI_HEADED!=='1',args:process.env.UI_HEADED==='1'?[]:['--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true});await context.route('**/*',async r=>{try{assert.equal(allowed(r.request().url()).origin,base);await r.continue()}catch(e){results.route_errors.push(e.message);await r.abort('blockedbyclient')}});const page=await context.newPage();page.on('pageerror',e=>results.errors.push(e.message));
 const response=await page.goto(base+'/campus-plan.html',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);const atlas=page.locator('.technical-atlas[data-figure="TA-20"]');await atlas.waitFor();await atlas.locator('img').evaluate(i=>i.decode());assert.equal(await page.locator('.technical-atlas').count(),1);assert.equal(await atlas.locator('img').getAttribute('src'),'/assets/technical-atlas/campus-plan-v1-preview.svg');assert.match(await atlas.locator('figcaption').textContent(),/UPS只见顶面/);assert.match(await atlas.locator('figcaption').textContent(),/无北向、比例尺或真实尺寸/);
 for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);assert.ok(await atlas.locator('img').evaluate(i=>i.complete&&i.naturalWidth===1536&&i.naturalHeight===1024));assert.equal(await atlas.locator('figure>a').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 249, 242)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok((await atlas.boundingBox()).width<=width);await page.evaluate(()=>scrollTo(0,0));const file=`campus-plan-${width}-${theme}.png`;await page.screenshot({path:path.join(out,file),fullPage:true});results.views.push({width,theme,file,fullHeight:await page.evaluate(()=>document.documentElement.scrollHeight)});}
 await page.setViewportSize({width:360,height:800});const header=await page.locator('#ui-skinbar').boundingBox();assert.ok(header.height<=90,'shared phone header remains compact');results.phone_header_360=header;await atlas.locator('summary').click();assert.equal(await atlas.locator('li').count(),7);await atlas.locator('summary').click();
 const popupWait=page.waitForEvent('popup');await atlas.getByRole('link',{name:'放大查看',exact:true}).click();const popup=await popupWait;await popup.waitForLoadState('domcontentloaded');const full=await popup.locator('svg').evaluate(n=>n.outerHTML);assert.equal(await popup.locator('.callout path').count(),12);assert.equal(await popup.locator('text').count(),39);assert.equal(await popup.locator('.tray-projection[data-physical="false"]').count(),4);const native=fs.readFileSync(path.join(root,'web/assets/technical-atlas/campus-plan-v1.png'));assert.deepEqual(Buffer.from((await popup.locator('svg>image').getAttribute('href')).split(',')[1],'base64'),native);await popup.close();
 // Independent full SVG asset canvas on actual origin, not substitute product implementation.
 const asset=await context.newPage();await asset.setViewportSize({width:1536,height:1024});await asset.goto(base+'/healthz');await asset.setContent('<link rel="stylesheet" href="'+base+'/assets/fonts/fonts.css"><style>body{margin:0}svg{display:block}</style>'+full);await asset.evaluate(()=>document.fonts.ready);const scan=await asset.evaluate(()=>{const t=[...document.querySelectorAll('text')].map(n=>{const b=n.getBBox();return{text:n.textContent,x:b.x,y:b.y,w:b.width,h:b.height}});return{outside:t.filter(b=>b.x<0||b.y<0||b.x+b.w>1536||b.y+b.h>1024),overlaps:t.flatMap((a,i)=>t.slice(i+1).filter(b=>a.x<b.x+b.w&&b.x<a.x+a.w&&a.y<b.y+b.h&&b.y<a.y+a.h).map(b=>[a.text,b.text])),fontsReady:document.fonts.check('17px "Noto Sans SC"')}});assert.deepEqual(scan.outside,[]);assert.deepEqual(scan.overlaps,[]);assert.ok(scan.fontsReady);results.full_svg={labels:12,texts:39,scan};await asset.locator('svg').screenshot({path:path.join(out,'campus-plan-full-svg-1536.png')});await asset.close();
 for(const[label,file]of[['下载标注图','campus-plan-v1.svg'],['下载无字底图','campus-plan-v1.png']]){const pending=page.waitForEvent('download');await atlas.getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(d.suggestedFilename(),file);const b=fs.readFileSync(await d.path()),expected=fs.readFileSync(path.join(root,'web/assets/technical-atlas',file));assert.equal(hash(b),hash(expected));results.downloads.push({file,bytes:b.length,sha256:hash(b)})}
 // Real related links open the original interactive routes; default/source mode is not rebound to a bitmap.
 await page.setViewportSize({width:1280,height:900});for(const[id,title,query]of[['TA-18','园区装配全景',''],['TA-19','园区分层爆炸图','?x=70']]){const l=atlas.locator(`[data-related-figure="${id}"]`);assert.equal(await l.getAttribute('href'),'/bom3d.html'+query);const wait=page.waitForEvent('popup');await l.click();const p=await wait;await p.waitForLoadState('domcontentloaded');await p.locator('.ui-viewer-controls h1').filter({hasText:title}).waitFor();await p.locator('#cv').waitFor();await p.waitForFunction(()=>{const c=document.querySelector('#cv');try{return c&&c.width>0&&c.toDataURL('image/png').length>20000}catch{return false}});assert.equal(await p.locator('a[href="/campus-plan.html"]').count(),1);await p.screenshot({path:path.join(out,id+'-linked-3d-1280.png')});results.views.push({related:id,url:p.url(),file:id+'-linked-3d-1280.png'});await p.close();}
 // Default independent category/TA12 remains its own artwork. No new category identity is invented.
 await page.goto(base+'/server-plan.html');await page.locator('.technical-atlas[data-figure="TA-12"]').waitFor();assert.equal(await page.locator('[data-figure="TA-20"]').count(),0);await page.goto(base+'/bom.html#ssd');await page.locator('.technical-atlas[data-figure="TA-01"]').waitFor();assert.equal(await page.locator('[data-figure="TA-20"]').count(),0);results.default_scope_isolation=true;
 // Independently rebuild the unchanged actual public factory, at exact homes, with the recorded strict native camera.
 await page.route('**/assets/campus-assembly.js',async route=>{try{assert.equal(allowed(route.request().url()).origin,base);const headers={...route.request().headers()};delete headers['if-none-match'];delete headers['if-modified-since'];const response=await route.fetch({headers,maxRedirects:0}),body=await response.body();assert.equal(response.status(),200,'actual factory full200');assert.ok(body.length>0,'actual factory nonempty');results.sources.push({url:route.request().url(),resourceType:route.request().resourceType(),status:response.status(),bytes:body.length,sha256:hash(body),conditional_headers_removed:true,fulfilled_unchanged_original_bytes:true});await route.fulfill({response,body})}catch(e){results.route_errors.push(e.message);await route.abort('failed')}});
 await page.goto(base+'/healthz');await page.setContent('<script type="importmap">{"imports":{"three":"'+base+'/assets/vendor/three.module.js"}}</script>');
 results.projection=await page.evaluate(async({proof,labels})=>{const THREE=await import('three');const route='/assets/campus-assembly.js',r=await fetch(route,{cache:'no-store'});if(r.status!==200)throw Error('factoryHTTP'+r.status);const b=await r.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',b),sha=[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join('');const{buildCampusAssembly}=await import(route);const picks=[],a=buildCampusAssembly({THREE,material:(c,o)=>new THREE.MeshBasicMaterial({color:c,...o}),tag:(m,p)=>{m.userData.part=p;picks.push(m)}});a.explode(0);for(const i of a.instances)if(proof.omittedInstances.includes(i.id))i.object.visible=false;a.root.updateMatrixWorld(true);const s=proof.camera,c=new THREE.OrthographicCamera(s.left,s.right,s.top,s.bottom,s.near,s.far);c.position.set(...s.position);c.up.set(...s.up);c.lookAt(new THREE.Vector3(...s.target));c.updateMatrixWorld(true);c.updateProjectionMatrix();const visible=picks.filter(m=>{let o=m;while(o){if(!o.visible)return false;o=o.parent}return true}),triangle=new THREE.Triangle(),closest=new THREE.Vector3();function distance(instance,p){let min=Infinity;instance.object.traverse(m=>{if(!m.isMesh)return;const g=m.geometry,ps=g.attributes.position,ix=g.index,count=ix?ix.count:ps.count;for(let n=0;n<count;n+=3){const ids=[0,1,2].map(k=>ix?ix.getX(n+k):n+k);triangle.a.fromBufferAttribute(ps,ids[0]).applyMatrix4(m.matrixWorld);triangle.b.fromBufferAttribute(ps,ids[1]).applyMatrix4(m.matrixWorld);triangle.c.fromBufferAttribute(ps,ids[2]).applyMatrix4(m.matrixWorld);triangle.closestPointToPoint(p,closest);min=Math.min(min,p.distanceTo(closest))}});return min}
 const checks=[];for(const l of labels.labels){const instance=a.instances.find(i=>i.id===l.instance),world=new THREE.Vector3(...l.local).applyMatrix4(instance.object.matrixWorld),v=world.clone().project(c),pixel=[(v.x+1)*768,(1-v.y)*512],ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(v.x,v.y),c);const hit=ray.intersectObjects(visible,true)[0];checks.push({num:l.num,instance:l.instance,role:l.anchor_role,world:world.toArray(),projection_error:Math.hypot(...pixel.map((n,k)=>n-l.source_anchor[k])),surface_distance:l.anchor_role==='actual visible top surface'?distance(instance,world):null,top_hit:hit?.object.userData.campusInstance,top_hit_distance:hit?hit.point.distanceTo(world):null})}
 const floorBounds=new THREE.Box3().setFromObject(a.instances.find(i=>i.id==='campus/building-base').object),rect=[[floorBounds.min.x,floorBounds.min.z],[floorBounds.max.x,floorBounds.min.z],[floorBounds.max.x,floorBounds.max.z],[floorBounds.min.x,floorBounds.max.z]].map(([x,z])=>{const v=new THREE.Vector3(x,floorBounds.max.y,z).project(c);return[(v.x+1)*768,(1-v.y)*512]}),instances=a.instances.map(i=>({id:i.id,home:i.home.toArray(),position:i.object.position.toArray(),visible:i.object.visible})),vertices=a.instances.reduce((sum,i)=>sum+i.object.userData.geometryPacking.packedVertices,0);a.dispose();a.dispose();return{factory:{route,status:r.status,bytes:b.byteLength,sha256:sha},direction:c.getWorldDirection(new THREE.Vector3()).toArray(),projection:c.type,instances,sourceMeshes:picks.length,visibleMeshes:visible.length,vertices,anchors:checks,rectangle:rect,rectangle_source_world_bounds:{min:floorBounds.min.toArray(),max:floorBounds.max.toArray()},disposed_twice:true}}, {proof,labels});
 const g=results.projection;assert.equal(g.factory.sha256,proof.source[0].sha256);const executedFactory=results.sources.filter(s=>s.resourceType==='script');assert.equal(executedFactory.length,1,'one actualexecutedmodule body');for(const s of results.sources)assert.equal(s.sha256,g.factory.sha256,'same200bytes fetched/executed');assert.equal(g.projection,'OrthographicCamera');assert.ok(Math.abs(g.direction[0])<1e-12&&Math.abs(g.direction[1]+1)<1e-12&&Math.abs(g.direction[2])<1e-12);assert.equal(g.instances.length,32);assert.equal(g.sourceMeshes,152);assert.equal(g.visibleMeshes,142);assert.equal(g.vertices,194916);for(const i of g.instances)assert.deepEqual(i.position,i.home);for(const a of g.anchors){assert.ok(a.projection_error<1e-8,'exactprojection'+a.num);if(a.role==='actual visible top surface'){assert.ok(a.surface_distance<1e-5,'actualsurface'+a.num+' '+a.surface_distance);assert.equal(a.top_hit,a.instance,'visiblefromtop'+a.num);assert.ok(a.top_hit_distance<1e-5,'topactualsurface'+a.num+' '+a.top_hit_distance)}else assert.ok(['10','11'].includes(a.num))}assert.equal(g.anchors.filter(a=>a.surface_distance!==null).length,10);const[tl,tr,br,bl]=g.rectangle;assert.ok(Math.abs(tl[1]-tr[1])<1e-9&&Math.abs(bl[1]-br[1])<1e-9&&Math.abs(tl[0]-bl[0])<1e-9&&Math.abs(tr[0]-br[0])<1e-9);assert.ok(Math.abs((tr[0]-tl[0])-(br[0]-bl[0]))<1e-9);
 assert.deepEqual(results.errors,[]);assert.deepEqual(results.route_errors,[]);results.status='PASS';console.log('TA20 public:4views,fullSVG/39texts/12labels,dualdownloadSHA,360header,original3Dlinks,strictprojection/32homes/10actualtops+2derivedprojections/oldscope PASS');
 }catch(e){results.status='FAIL';results.failure=e.stack||String(e);throw e}finally{results.finished_at=new Date().toISOString();fs.writeFileSync(path.join(out,'campus-plan-results.json'),JSON.stringify(results,null,2)+'\n');if(browser)await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
