/* Independent TA15 native illustration, editable labels and real downloads. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright'),{PNG}=require('pngjs');
const root=path.join(__dirname,'..'),base=process.env.UI_BASE_URL,hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});try{
 const out=process.env.REVIEW_SCREENSHOTS,results={observed_at:new Date().toISOString(),base,views:[],downloads:[],page_errors:[]},page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1,acceptDownloads:true});page.on('pageerror',e=>results.page_errors.push(e.message));
 await page.goto(base+'/chip-atlas.html',{waitUntil:'domcontentloaded'});const atlas=page.locator('.technical-atlas[data-figure="TA-15"]');await atlas.waitFor();await atlas.locator('img').evaluate(i=>i.decode());assert.equal(await page.locator('.technical-atlas').count(),1);assert.equal(await atlas.locator('img').getAttribute('src'),'/assets/technical-atlas/chip-package-v1-preview.svg');assert.match(await atlas.locator('figcaption').textContent(),/原生1536.*同一.*非OEM.*制造/);
 for(const width of [1280,390])for(const theme of ['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);assert.ok(await atlas.locator('img').evaluate(i=>i.complete&&i.naturalWidth===1536&&i.naturalHeight===1024));assert.equal(await atlas.locator('figure>a').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 249, 242)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>scrollTo(0,0));const file='chip-package-'+width+'-'+theme+'.png';if(out)await page.screenshot({path:path.join(out,file),fullPage:true});results.views.push({width,theme,file});}
 await page.setViewportSize({width:360,height:800});const bar=await page.locator('#ui-skinbar').boundingBox();assert.ok(bar.height<=86,'shared two-row phone bar');results.phone_bar={width:360,height:bar.height};await atlas.locator('summary').click();assert.equal(await atlas.locator('li').count(),6);await atlas.locator('summary').click();
 const pending=page.waitForEvent('popup');await atlas.getByRole('link',{name:'放大查看',exact:true}).click();const full=await pending;await full.waitForLoadState('domcontentloaded');assert.equal(await full.locator('#editable-labels>g').count(),8);assert.equal(await full.locator('#editable-leaders path').count(),8);const raw=await full.locator('svg').evaluate(e=>e.outerHTML),embedded=await full.locator('svg>image').getAttribute('href'),native=fs.readFileSync(path.join(root,'web/assets/technical-atlas/chip-package-v1.png'));assert.deepEqual(Buffer.from(embedded.split(',')[1],'base64'),native);results.native_png_sha256=hash(native);
 const labels=await full.locator('#editable-labels text').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBBox();return{id:n.id,x:b.x,y:b.y,width:b.width,height:b.height}}));for(const b of labels)assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=1536&&b.y+b.height<=1024,'label in bounds '+b.id);for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],b=labels[j];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,'labels do not overlap');}results.labels=labels;
 if(out){const preview=await browser.newPage({viewport:{width:1536,height:1024},deviceScaleFactor:1});await preview.goto(base+'/chip-atlas.html');await preview.setContent('<!doctype html><head><link rel="stylesheet" href="'+base+'/assets/fonts/fonts.css"><style>body{margin:0}svg{display:block}</style></head><body>'+raw+'</body>');await preview.evaluate(()=>document.fonts.ready);await preview.locator('svg').screenshot({path:path.join(out,'chip-package-full-svg.png')});await preview.close();}await full.close();
 for(const [label,file] of [['下载标注图','chip-package-v1.svg'],['下载无字底图','chip-package-v1.png']]){const pending=page.waitForEvent('download');await atlas.getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(await d.failure(),null);assert.equal(d.suggestedFilename(),file);const b=fs.readFileSync(await d.path());assert.equal(hash(b),hash(fs.readFileSync(path.join(root,'web/assets/technical-atlas',file))));results.downloads.push({file,bytes:b.length,sha256:hash(b)});}
 await page.goto(base+'/bom.html#hbm');await page.locator('.technical-atlas[data-figure="TA-05"]').waitFor();assert.equal(await page.locator('.technical-atlas[data-figure="TA-15"]').count(),0,'category HBM master unchanged');await page.locator('#c-gpu').click();await page.locator('.technical-atlas[data-figure="TA-04"]').waitFor();const nativePage=await browser.newPage({viewport:{width:1536,height:1024},deviceScaleFactor:1});nativePage.on('pageerror',e=>results.page_errors.push(e.message));await nativePage.route('**/ta14-native-check',r=>r.fulfill({contentType:'text/html',body:'<script type="importmap">{"imports":{"three":"/assets/vendor/three.module.js"}}</script><canvas></canvas><script type="module">import{renderNativeChipPackage}from"/assets/chip-package-generator.js";const r=renderNativeChipPackage(document.querySelector("canvas"));const png=r.composition();window.nativeResult={png,evidence:r.evidence,orthographic:r.camera.isOrthographicCamera};r.dispose();</script>'}));await nativePage.goto(base+'/ta14-native-check');await nativePage.waitForFunction(()=>!!window.nativeResult);const reproduced=await nativePage.evaluate(()=>window.nativeResult);assert.equal(reproduced.orthographic,true);assert.deepEqual(reproduced.evidence.native_pixels,[1536,1024]);assert.deepEqual(reproduced.evidence.inset.native_pixels,[380,330]);assert.deepEqual(reproduced.evidence.contact_detail.native_pixels,[380,110]);assert.deepEqual(reproduced.evidence.underside.native_pixels,[380,210]);assert.equal(reproduced.evidence.inset.instance,'package/hbm-2');assert.equal(reproduced.evidence.contact_detail.instance,'package/hbm-2');assert.equal(reproduced.evidence.underside.instance,'package/substrate');assert.equal(reproduced.evidence.counts.HBMStacks,4);const actual=PNG.sync.read(Buffer.from(reproduced.png.split(',')[1],'base64')),expected=PNG.sync.read(native);let sum=0,large=0;for(let i=0;i<actual.data.length;i+=4){let max=0;for(let k=0;k<3;k++){const delta=Math.abs(actual.data[i+k]-expected.data[i+k]);sum+=delta;max=Math.max(max,delta);}if(max>16)large++;}const mean=sum/(1536*1024*3),fraction=large/(1536*1024);assert.ok(mean<=1.5&&fraction<=.01,'native render pixel comparison '+JSON.stringify({mean,fraction}));results.native_reproduction={evidence:reproduced.evidence,mean_absolute_rgb_delta:mean,large_delta_pixel_fraction:fraction,scope:'Exact native dimensions and same-geometry insets; bounded GPU pixel differences, not a substitute for original visual review'};await nativePage.close();assert.deepEqual(results.page_errors,[]);if(out)fs.writeFileSync(path.join(out,'chip-package-atlas-results.json'),JSON.stringify(results,null,2)+'\n');console.log('PASS TA15 reader entry: native master/8labels8leaders, desktop/phone themes, shared bar, full downloads and existing TA04/TA05 bindings');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
