/* TA15: same-instance contact correspondence, independent closeup, real picks and camera ownership. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright'),{PNG}=require('pngjs');
const base=process.env.UI_BASE_URL,out=process.env.REVIEW_SCREENSHOTS,scenario=process.argv[2]||'all';assert.ok(['all','views','assembly'].includes(scenario));
(async()=>{const browser=await chromium.launch({headless:process.env.UI_HEADED!=='1',args:process.env.UI_HEADED==='1'?[]:['--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true}),errors=[],results=[],sources=[];page.on('pageerror',e=>errors.push(e.message));
 async function source(r){const headers={...r.request().headers()};delete headers['if-none-match'];delete headers['if-modified-since'];const res=await r.fetch({headers}),body=await res.text();sources.push({url:r.request().url(),status:res.status(),bytes:Buffer.byteLength(body)});assert.equal(res.status(),200);assert.ok(body.length);return{res,body};}
 await page.route(/\/assets\/part-inspector\.js(?:\?[^#]*)?$/,async r=>{const{res,body}=await source(r),next=body.replace('return {canvas: iCv,','return {objectsForTest:()=>iGroup?.children||[],canvas: iCv,');assert.notEqual(next,body);await r.fulfill({response:res,body:next});});
 await page.route(/\/rack3d\.html/,async r=>{const{res,body}=await source(r),next=body.replace('</script>\n</body>','globalThis.__chipTest={THREE,rack,chipAssembly,chipMode,rackExplodedMode,rackOverviewMode,serverMode,pickables,sceneModels,scene,renderer,composer,canvas,camera,controls,sceneView,inspector,currentPartMeshes,disposePage};\n</script>\n</body>');assert.notEqual(next,body);await r.fulfill({response:res,body:next});});
 const screenshot=async name=>{if(out)await page.screenshot({path:path.join(out,name+'.png')});};
 const stage=async t=>page.locator('#explode').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},t);
 const open=async()=>{if(!await page.locator('[data-responsive-panel]').evaluate(e=>e.open))await page.getByLabel('展开或收起场景控制').click();};
 async function fit(){await open();await page.locator('#fit-view').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
 await page.goto(base+'/rack3d.html?x=90',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!globalThis.__chipTest);assert.deepEqual(await page.evaluate(()=>[__chipTest.chipMode,__chipTest.rackExplodedMode,__chipTest.rackOverviewMode,__chipTest.serverMode]),[true,false,false,false]);assert.equal(await page.locator('#explode').inputValue(),'90');assert.equal(await page.locator('#explode').getAttribute('aria-label'),'封装层次虚拟展开');
 await page.locator('.drill').waitFor({state:'attached'});await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const initial=await page.evaluate(()=>({p:__chipTest.camera.position.toArray(),t:__chipTest.controls.target.toArray()}));await fit();const explicit=await page.evaluate(()=>({p:__chipTest.camera.position.toArray(),t:__chipTest.controls.target.toArray()}));for(const k of['p','t'])explicit[k].forEach((x,i)=>assert.ok(Math.abs(x-initial[k][i])<.001));results.push({label:'authored x90 initial view equals explicit fit',initial,explicit});
 if(scenario!=='views'){
 const structure=await page.evaluate(()=>{const v=__chipTest,a=v.chipAssembly,all=[];a.root.traverse(o=>{if(o.isMesh)all.push(o)});return{counts:a.counts,meshes:all.length,picks:v.pickables.length,unique:new Set(v.pickables).size,models:v.sceneModels.objects().length,logic:a.logic.name,hbms:a.hbms.map(h=>({id:h.userData.instanceId,layers:h.children.filter(o=>/^DRAM-layer-/.test(o.name)).length,tsv:h.children.filter(o=>o.name==='internal-TSV').length})),ids:a.instances.map(i=>i.id),axes:a.instances.map(i=>i.axis.toArray())};});assert.deepEqual(structure.counts,{logicDies:1,HBMStacks:4,DRAMLayersPerStack:8,internalTSVsInCutaway:6,substrates:1,interposers:1,BGABalls:280});assert.equal(structure.meshes,structure.picks);assert.equal(structure.meshes,structure.unique);assert.equal(structure.models,0);assert.ok(structure.hbms.every(h=>h.layers===8));assert.deepEqual(structure.hbms.map(h=>h.tsv),[0,6,0,0]);assert.equal(new Set(structure.ids).size,5);assert.ok(structure.axes.every(a=>JSON.stringify(a)==='[0,1.7,0]'));results.push({label:'actual generic package geometry and unique local instances',...structure});
 await stage(0);const home=await page.evaluate(()=>{
  const v=__chipTest,a=v.chipAssembly,T=v.THREE;a.root.updateMatrixWorld(true);
  const world=o=>o.getWorldPosition(new T.Vector3());
  const bounds=o=>{o.geometry.computeBoundingBox();return o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld)};
  const pads=a.interposer.children.filter(o=>o.name==='corresponding-contact-pad');let pairs=0,maxGap=0,maxPlanar=0;
  for(const i of a.instances)for(const c of i.object.children.filter(o=>o.name==='die-underside-contact')){
   const p=world(c),pad=pads.reduce((best,n)=>{const q=world(n),d=Math.hypot(q.x-p.x,q.z-p.z);return !best||d<best.d?{o:n,d}:best},null);
   pairs++;maxGap=Math.max(maxGap,Math.abs(bounds(c).min.y-bounds(pad.o).max.y));maxPlanar=Math.max(maxPlanar,pad.d);
  }
  const c4=[];a.interposer.getObjectByName('interposer-underside-contacts').traverse(o=>{if(o.isMesh)c4.push(o)});
  // Derive both mating surfaces from real geometry and world transforms. No radius/height is copied from production.
  const substrateTop=bounds(a.substrate.getObjectByName('organic-package-substrate')).max.y;
  const interposerBottom=bounds(a.interposer.getObjectByName('silicon-interposer')).min.y;
  const c4Gap=Math.max(...c4.map(c=>Math.abs(bounds(c).min.y-substrateTop)));
  const c4UpperGap=Math.max(...c4.map(c=>Math.abs(bounds(c).max.y-interposerBottom)));
  const cut=a.hbms[1],posts=cut.children.filter(o=>o.name==='internal-TSV');
  const postTop=Math.max(...posts.map(o=>bounds(o).max.y)),siliconTop=bounds(cut.getObjectByName('DRAM-layer-8')).max.y;
  globalThis.__chipHome=a.instances.map(i=>({id:i.id,p:i.object.getWorldPosition(new T.Vector3()),r:i.object.quaternion.clone()}));
  return{pairs,maxGap,maxPlanar,c4Count:c4.length,c4Gap,c4UpperGap,substrateTop,interposerBottom,postTop,siliconTop,measurement:'Actual mesh geometry boundingBox transformed to world; no copied sphere radius or plate thickness',substrate:a.substrate.position.toArray()};
 });
 assert.equal(home.pairs,200);assert.ok(home.maxGap<1e-8&&home.maxPlanar<1e-8&&home.c4Gap<1e-8&&home.c4UpperGap<1e-8);
 assert.equal(home.c4Count,108);assert.ok(home.postTop<=home.siliconTop);
 results.push({label:'all200 actual paired contacts touch their own pads; C4 touches both substrate and interposer; TSV stays in silicon',...home});
 for(const t of[45,100,0,90]){await stage(t);const moved=await page.evaluate(()=>{const v=__chipTest,a=v.chipAssembly,T=v.THREE;const rows=a.instances.map((i,k)=>{const p=i.object.getWorldPosition(new T.Vector3()),h=__chipHome[k];return{id:i.id,dx:p.x-h.p.x,dz:p.z-h.p.z,dy:p.y-h.p.y,rotation:i.object.quaternion.angleTo(h.r),local:i.object.position.toArray()}});return{rows,substrate:a.substrate.position.toArray(),layer:a.interposer.position.toArray()};});assert.ok(moved.rows.every(r=>Math.abs(r.dx)<1e-8&&Math.abs(r.dz)<1e-8&&r.rotation<1e-8));assert.ok(moved.rows.every(r=>Math.abs(r.dy-moved.rows[0].dy)<1e-8));assert.deepEqual(moved.substrate,home.substrate);results.push({label:'all5 devices retain full2D contact projection and one common separation, stage'+t,...moved});}
 }
 if(scenario!=='assembly')for(const width of[1280,390])for(const theme of['light','dark'])for(const t of[0,100]){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await stage(t);await fit();if(width===390)await page.getByLabel('展开或收起场景控制').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const coverage=await page.evaluate(()=>{const v=__chipTest,c=v.canvas.getBoundingClientRect(),h=document.querySelector('.hud').getBoundingClientRect();let left=Infinity,right=-Infinity,top=Infinity,bottom=-Infinity;v.scene.updateMatrixWorld(true);for(const m of v.pickables){m.geometry.computeBoundingBox();const b=m.geometry.boundingBox;for(const x of[b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z]){const p=new v.THREE.Vector3(x,y,z).applyMatrix4(m.matrixWorld).project(v.camera),sx=c.x+(p.x+1)*c.width/2,sy=c.y+(1-p.y)*c.height/2;left=Math.min(left,sx);right=Math.max(right,sx);top=Math.min(top,sy);bottom=Math.max(bottom,sy);}}return{left,right,top,bottom,canvas:{left:c.left,right:c.right,top:c.top,bottom:c.bottom},hud:{left:h.left,right:h.right,top:h.top,bottom:h.bottom},legend:document.querySelector('.hud summary .rack-exploded-legend').textContent};});assert.ok(coverage.left>=coverage.canvas.left&&coverage.right<=coverage.canvas.right&&coverage.top>=coverage.canvas.top&&coverage.bottom<=coverage.canvas.bottom);assert.ok(coverage.right<=coverage.hud.left||coverage.left>=coverage.hud.right||coverage.bottom<=coverage.hud.top||coverage.top>=coverage.hud.bottom,'actual geometry clears controls '+JSON.stringify(coverage));if(width===390){assert.ok(coverage.right-coverage.left>=390*.75);assert.ok(await page.locator('.hud summary .rack-exploded-legend').isVisible());assert.match(coverage.legend,/① 逻辑裸片.*② 四组HBM.*③ 硅中介层.*④ 基板.*⑤ 底部焊球/);}const png=PNG.sync.read(Buffer.from((await page.evaluate(()=>{__chipTest.composer.render();return __chipTest.canvas.toDataURL('image/png')})).split(',')[1],'base64')),colors=new Set();for(let i=0;i<png.data.length;i+=16)colors.add(png.data[i]+','+png.data[i+1]+','+png.data[i+2]);assert.ok(colors.size>50);await screenshot('chip-package-'+width+'-'+theme+'-'+t);results.push({label:'actual rendered view clears canvas and persistent controls, with number mapping',width,theme,stage:t,colors:colors.size,...coverage});}
 if(scenario!=='views'){
 await page.setViewportSize({width:1280,height:900});await page.locator('#ui-appearance').selectOption('light');await stage(100);await fit();await page.locator('#chip-package-dossier').click();await page.locator('#dossier canvas').waitFor();assert.equal(await page.locator('#dossier .technical-atlas').getAttribute('data-figure'),'TA-15');const wholeCount=await page.evaluate(()=>__chipTest.pickables.length);assert.equal(await page.evaluate(()=>__chipTest.inspector.objectsForTest().length),wholeCount);assert.match(await page.locator('#dossier').textContent(),/一块逻辑裸片、四组HBM/);await page.locator('#dossier .insp').scrollIntoViewIfNeeded();await screenshot('chip-package-whole-inspector');await page.getByRole('button',{name:'关闭部件档案'}).click();results.push({label:'complete package dossier includes actual all4 stacks and connection layers',meshes:wholeCount});
 for(const name of['logic-die','hbm-3','substrate']){const p=await page.evaluate(name=>{const v=__chipTest,g=v.rack.getObjectByName(name),q=g.localToWorld(new v.THREE.Vector3(name==='substrate'?3.8:0,name==='substrate'?.155:name==='logic-die'?.125:.54,name==='substrate'?2.8:0)).project(v.camera),rect=v.canvas.getBoundingClientRect();let n=0;g.traverse(m=>{if(m.isMesh)n++});return{x:rect.x+(q.x+1)*rect.width/2,y:rect.y+(1-q.y)*rect.height/2,count:n,id:g.userData.instanceId};},name);await page.mouse.move(p.x,p.y);await page.mouse.click(p.x,p.y);await page.locator('#dossier canvas').waitFor();assert.equal(await page.evaluate(()=>__chipTest.inspector.objectsForTest().length),p.count,name);const text=await page.locator('#dossier').textContent();assert.match(text,/示例|通用/);assert.match(text,/未知|未指定/);await screenshot('chip-package-instance-'+name);const pending=page.waitForEvent('download');await page.locator('#atlas-export').click();const d=await pending;assert.equal(await d.failure(),null);const svg=fs.readFileSync(await d.path(),'utf8');assert.ok(svg.includes('data-object-id="'+p.id+'"'));assert.ok(svg.includes('通用芯片封装层次图册'));results.push({label:'real canvas pick and current-view export retain one instance',name,...p});await page.getByRole('button',{name:'关闭部件档案'}).click();}
 await page.evaluate(()=>{const v=__chipTest;v.sceneView.takeControl();v.camera.position.x+=1;v.controls.target.x+=1;globalThis.__owned={p:v.camera.position.toArray(),t:v.controls.target.toArray()};});await stage(0);await page.setViewportSize({width:1000,height:800});await page.evaluate(async()=>{await __chipTest.sceneModels.reload();__chipTest.sceneView.refresh()});const owned=await page.evaluate(()=>({before:__owned,after:{p:__chipTest.camera.position.toArray(),t:__chipTest.controls.target.toArray()}}));for(const k of['p','t'])owned.after[k].forEach((n,i)=>assert.ok(Math.abs(n-owned.before[k][i])<.001));results.push({label:'manual camera survives stage resize and late refresh'});
 const released=await page.evaluate(async()=>{const v=__chipTest,gs=new Set(),ms=new Set();v.rack.traverse(o=>{if(o.isMesh){gs.add(o.geometry);[].concat(o.material).forEach(m=>ms.add(m))}});let g=0,m=0,renders=0;gs.forEach(o=>o.addEventListener('dispose',()=>g++));ms.forEach(o=>o.addEventListener('dispose',()=>m++));const render=v.composer.render.bind(v.composer);v.composer.render=(...args)=>{renders++;return render(...args)};v.disposePage();v.disposePage();const n=renders;await new Promise(r=>setTimeout(r,80));return{geometries:gs.size,materials:ms.size,g,m,after:renders-n,picks:v.pickables.length,parent:!!v.rack.parent,labels:document.querySelectorAll('.atlas-scene-labels').length};});assert.equal(released.g,released.geometries);assert.equal(released.m,released.materials);assert.equal(released.after,0);assert.equal(released.picks,0);assert.equal(released.parent,false);assert.equal(released.labels,0);results.push({label:'owned geometry/material resources release once and RAF stops',...released});
 for(const[url,want]of[['/rack3d.html?x=0',[false,true,false,false]],['/rack3d.html?x=35',[false,false,true,false]],['/rack3d.html?view=legacy&x=90',[false,false,false,false]],['/rack3d.html?x=55',[false,false,false,true]],['/rack3d.html?node=part:gpu',[false,false,false,false]],['/rack3d.html?x=90&node=part:ssd#ssd',[false,false,false,false]],['/rack3d.html?view=chip&explode=0',[true,false,false,false]]]){await page.goto(base+url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!globalThis.__chipTest);assert.deepEqual(await page.evaluate(()=>[__chipTest.chipMode,__chipTest.rackOverviewMode,__chipTest.rackExplodedMode,__chipTest.serverMode]),want);assert.ok(await page.evaluate(()=>__chipTest.pickables.length>0));if(want[0])assert.equal(await page.locator('#explode').inputValue(),'0');results.push({label:'retained independent and legacy route',url,want});}
 }
 assert.deepEqual(errors,[]);if(out)fs.writeFileSync(path.join(out,'chip-package-results'+(scenario==='all'?'':'-'+scenario)+'.json'),JSON.stringify({observed_at:new Date().toISOString(),scenario,results,sources,page_errors:errors},null,2)+'\n');console.log('PASS TA15 '+scenario+' real package, contact, views, picks, camera and release');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
