/* Dashboard: one tree, five columns, four questions. Root matrix, system drill-down, part page, no page errors. */
const {chromium}=require('playwright');const assert=require('assert');
(async()=>{
 const base=process.env.UI_BASE_URL||'http://127.0.0.1:8882';
 const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/node.html');await page.locator('#matrix tbody tr').first().waitFor();
 assert.equal(await page.locator('#matrix tbody tr:visible').count(),6,'five systems plus the site-rights row; IT collapsed');
 assert.equal(await page.locator('#matrix td.cell').count(),50,'ten rows (four IT children hidden) by five variable classes');
 await page.locator('#matrix .it-toggle').click();await page.locator('#matrix.it-open').waitFor();
 assert.equal(await page.locator('#matrix tbody tr:visible').count(),10,'IT expands into four subsystems');
 assert.equal(await page.locator('.acct').count(),3,'cost, revenue and return above the five columns');
 assert.equal(await page.locator('#five .col').count(),5);
 assert.equal(await page.locator('#account a[href="ledger.html"]').count(),1,'price column links to the one ledger expansion');
 await page.locator('#grid .board').waitFor();
 assert.match(await page.locator('#grid .board').innerText(),/工单/,'delivery board migrated from the retired home page');
 assert.ok(await page.locator('#news').isVisible(),'news timeline on the root node');
 for(const id of ['p1','p2','p3','p4'])assert.ok(await page.locator('#'+id+' > h2').isVisible(),id);
 assert.ok((await page.locator('#matrix td.cell.needed').count())>0,'grey cells are the acquisition worklist');
 await page.locator('#matrix tbody tr.row-top').nth(1).locator('td.cell').nth(3).locator('a').click();
 await page.locator('#col-4.hl').waitFor();
 const url=new URL(page.url());assert.equal(url.searchParams.get('col'),'4');assert.match(url.searchParams.get('id'),/^system:/);
 await page.locator('#children table tbody tr').first().waitFor();
 assert.match(new URL(page.url()).searchParams.get('id'),/^system:power$/);
 assert.deepEqual((await page.locator('#children tr.chain-row th').allTextContents()).slice(0,3),['电网接入','变电','发电与储能'],'parts grouped along the energy-flow chain');
 await page.goto(base+'/node.html?id=system:it');await page.locator('#children table tbody tr').first().waitFor();
 assert.equal(await page.locator('#children table tbody tr').count(),4,'IT lists its four subsystems');
 await page.goto(base+'/node.html?id=part:transformer');await page.locator('#five .col').first().waitFor();
 assert.match(await page.locator('#head h1').textContent(),/变压器/);
 assert.match(await page.locator('#head .kind').first().textContent(),/变电/,'part page names its chain');
 assert.ok((await page.locator('#col-4 .kv').count())>0,'transformer lead time is a sourced time cell');
 assert.ok((await page.locator('#targets table tbody tr').count())>=3,'spec, price and lead-time targets');
 assert.ok((await page.locator('#factors .factor').count())>=1);
 await page.goto(base+'/node.html?id=site:grid');await page.locator('#five .col').first().waitFor();
 assert.match(await page.locator('#head h1').textContent(),/并网/);
 await page.goto(base+'/ledger.html');await page.locator('#calibration-table tbody tr').first().waitFor();
 assert.ok((await page.locator('#calibration-table tbody tr').count())>=8,'the three calibration anchors replace the old assumption bridge');
 assert.equal(await page.locator('#calibration-table .flag.no').count(),0,'one model reproduces all three');
 assert.equal(await page.locator('#views button').count(),4,'four views on the one model');
 assert.ok(await page.locator('#view-lifecycle.on').isVisible());await page.locator('#views button[data-view=ledgers]').click();await page.locator('#view-ledgers.on').waitFor();
 assert.equal(await page.locator('#model-inputs details').count(),5,'inputs grouped by the five variable classes');
 assert.equal(await page.locator('#presets button.active').textContent(),'基准 · AI 自建 · 北弗吉尼亚','the root account and the ledger share the one baseline');
 await page.goto(base+'/node.html?id=nope');await page.locator('#error .err').waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS dashboard: root matrix five systems (IT expands to four) plus site rights, drill-down keeps the column, chain-grouped parts, ledger, unknown node reports');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
