/* Dashboard: one tree, five columns, four questions. Root matrix, system drill-down, part page, no page errors. */
const {chromium}=require('playwright');const assert=require('assert');
(async()=>{
 const base=process.env.UI_BASE_URL||'http://127.0.0.1:8882';
 const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/node.html');await page.locator('#matrix tbody tr').first().waitFor();
 assert.equal(await page.locator('#matrix tbody tr:visible').count(),6,'five systems plus the site-rights row; IT collapsed');
 assert.equal(await page.locator('#matrix td.cell').count(),50,'ten rows (four IT children hidden) by five variable classes');
 await page.locator('#matrix .it-toggle').click();await page.locator('#matrix.it-open').waitFor();
 assert.equal(await page.locator('#matrix tbody tr:visible').count(),10,'IT expands into four subsystems');
 assert.equal(await page.locator('.acct').count(),3,'cost, revenue and return above the five columns');
 assert.equal(await page.locator('#five .col').count(),5);
 assert.equal(await page.locator('#account a[href="ledger.html"]').count(),1,'price column links to the one ledger expansion');
 await page.locator('#grid .board').waitFor();
 assert.match(await page.locator('#grid .board').innerText(),/目标表就是任务书/,'delivery board reads the target table, not workorders');
 assert.equal(await page.locator('#readings a').count(),4,'four readings (build / compose / operate / earn) under the account');
 assert.match(await page.locator('#matrix thead th').nth(1).innerText(),/目标 已有 \d+ · 缺 \d+/,'column coverage in the matrix header');
 assert.equal(await page.locator('.acct .evidence').count(),3,'each ledger level shows the evidence status of its inputs');
 assert.ok(await page.locator('#news').isVisible(),'news timeline on the root node');
 for(const id of ['p1','p2','p3','p4'])assert.ok(await page.locator('#'+id+' > h2').isVisible(),id);
 assert.ok((await page.locator('#matrix td.cell.needed').count())>0,'grey cells are the acquisition worklist');
 assert.ok((await page.locator('#matrix td.cell.registered').count())>0,'our own counts (parts, suppliers) are registered, never sourced');
 assert.equal(await page.locator('#matrix td.cell.sourced .c').filter({hasText:/部件数|供应商数|权利条目|持有方/}).count(),0,'no count cell is painted green');
 assert.match(await page.locator('#p2 .cov').last().innerText(),/已交付、未成序列.*只有登记数/,'legend names the four states plus registered');
 await page.locator('#targets table tbody tr').first().waitFor({state:'attached'});
 assert.ok((await page.locator('#targets td').filter({hasText:'待建队'}).count())>0,'rows owned by teams not yet connected show 待建队 instead of a due date');
 assert.ok((await page.locator('#targets td').filter({hasText:'人工登记'}).count())>0,'sourced rows say whether the series came from the registry');
 assert.match(await page.locator('#q4').innerText(),/已交付未成序列 \d+.*归待建队/,'root q4 counts delivered and not-connected rows');
 await page.locator('#matrix tbody tr.row-top').nth(1).locator('td.cell').nth(3).locator('a').click();
 await page.locator('#col-4.hl').waitFor();
 const url=new URL(page.url());assert.equal(url.searchParams.get('col'),'4');assert.match(url.searchParams.get('id'),/^system:/);
 await page.locator('#children table tbody tr').first().waitFor();
 assert.match(new URL(page.url()).searchParams.get('id'),/^system:power$/);
 assert.deepEqual((await page.locator('#children tr.chain-row th').allTextContents()).slice(0,3),['电网接入','变电','发电与储能'],'parts grouped along the energy-flow chain');
 await page.goto(base+'/node.html?col=4');await page.locator('#timeline .stage').first().waitFor();
 assert.equal(await page.locator('#timeline .stage').count(),6,'it怎么建: six build stages');
 assert.match(await page.locator('#timeline .stage').first().innerText(),/权利与审批/);
 assert.ok((await page.locator('#timeline .stage a.kv').count())>60,'every part and right sits in a stage');
 await page.goto(base+'/node.html?id=system:it');await page.locator('#children table tbody tr').first().waitFor();
 assert.equal(await page.locator('#children table tbody tr').count(),4,'IT lists its four subsystems');
 await page.goto(base+'/node.html?id=part:transformer');await page.locator('#five .col').first().waitFor();
 assert.match(await page.locator('#head h1').textContent(),/变压器/);
 assert.match(await page.locator('#head .kind').first().textContent(),/变电/,'part page names its chain');
 assert.ok((await page.locator('#col-4 .kv').count())>0,'transformer lead time is a sourced time cell');
 assert.ok((await page.locator('#col-5 a.chip[href^="product-catalog.html?c="]').count())>0,'suppliers on the fifth column open the actor page');
 assert.ok((await page.locator('#targets table tbody tr').count())>=4,'spec, operation, price and lead-time targets');
 assert.equal(await page.locator('#five a[href^="supply.html?"]').count(),5,'every column links to the acquisition page prefiltered by node and column');
 await page.locator('#evidence .ev-grid').waitFor();
 assert.equal(await page.locator('#evidence .col').count(),3,'questions, candidate evidence and one-hop relations on the part node');
 assert.ok((await page.locator('#evidence .chip a').count())>0,'suppliers and the chain are one hop away');
 assert.equal(await page.locator('a[href^="research.html"]').count(),0,'no link to the retired research page');
 assert.ok((await page.locator('#factors .factor').count())>=1);
 await page.goto(base+'/product-catalog.html?c=hitachi-energy');await page.locator('#catalog-title').waitFor();await page.locator('#research-details summary').click();await page.locator('#root .grid').waitFor();
 assert.ok((await page.locator('#root a[href^="node.html?id=part:"]').count())>0,'the actor page lists the parts it supplies');
 assert.equal(await page.locator('.kpi').count(),0,'no KPI grid, map or module blocks on the actor page');
 await page.goto(base+'/product-catalog.html?c=constellation-energy#ecosystem');await page.locator('#ecosystem').waitFor();
 assert.equal(await page.locator('#ecosystem article').count(),2,'new generation and existing supply are separate agreements');
 assert.match(await page.locator('#ecosystem').innerText(),/890 MW.*新增计划/);
 assert.match(await page.locator('#ecosystem').innerText(),/2700 MW.*既有电源协议/);
 assert.equal(await page.locator('#ecosystem [aria-label="地域对照"] tr').count(),4,'three states without inferred state allocations');
 assert.match(await page.locator('#ecosystem').innerText(),/不增加数据中心 IT GW/);
 assert.ok(await page.locator('#ecosystem a[href*="product-catalog.html?c=alphabet-google"]').count());
 for(const width of [390,1280]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.goto(base+'/node.html?id=site:grid');await page.locator('#five .col').first().waitFor();
 assert.match(await page.locator('#head h1').textContent(),/并网/);
 await page.goto(base+'/ledger.html');await page.locator('#calibration-table tbody tr').first().waitFor();
 assert.ok((await page.locator('#calibration-table tbody tr').count())>=8,'the three calibration anchors replace the old assumption bridge');
 assert.equal(await page.locator('#calibration-table .flag.no').count(),0,'one model reproduces all three');
 assert.equal(await page.locator('#views button').count(),4,'four views on the one model');
 assert.ok(await page.locator('#view-lifecycle.on').isVisible());await page.locator('#views button[data-view=ledgers]').click();await page.locator('#view-ledgers.on').waitFor();
 assert.equal(await page.locator('#model-inputs details').count(),5,'inputs grouped by the five variable classes');
 assert.equal(await page.locator('#presets button.active').textContent(),'基准 · AI 自建 · 北弗吉尼亚','the root account and the ledger share the one baseline');
 await page.goto(base+'/node.html?id=nope');await page.locator('#error .err').waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS dashboard: root matrix five systems (IT expands to four) plus site rights, drill-down keeps the column, chain-grouped parts, ledger, unknown node reports');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
