/* TA22/23 actual public only. No local product server, URL, fallback or CI registration. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright');
assert.equal(process.env.UI_BASE_URL,'https://inresearch.ai','Explicitly authorized actual public origin required');
const figure=process.env.TA_ENERGY_FIGURE;assert.ok(['TA-22','TA-23'].includes(figure));
const domain=figure==='TA-22'?'power':'thermal',total=figure==='TA-22'?19:15,missing=figure==='TA-22'?15:12,physical=figure==='TA-22'?8:11,probe=figure==='TA-22'?'transformer':'chiller',base=process.env.UI_BASE_URL,root=process.env.TA_ENERGY_SOURCE_ROOT||path.resolve(__dirname,'..'),D=path.join(root,'docs/design/technical-atlas',figure),out=process.env.REVIEW_SCREENSHOTS||'/private/tmp/'+domain+'-public-'+Date.now(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
fs.mkdirSync(out,{recursive:true});const results={figure,observed_at:new Date().toISOString(),base,views:[],downloads:[],sources:[],declared_resources:[],categories:[],errors:[],route_errors:[],resource_failures:[]};let browser;
(async()=>{try{
 browser=await chromium.launch({headless:process.env.UI_HEADED!=='1'});const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true});await context.route('**/*',async r=>{try{assert.equal(new URL(r.request().url()).origin,base);await r.continue()}catch(e){results.route_errors.push(e.message);await r.abort('blockedbyclient')}});
 const page=await context.newPage();page.on('pageerror',e=>results.errors.push(e.message));page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/assets/')&&r.status()>=400)results.resource_failures.push({url:r.url(),status:r.status()})});
 const first=await page.goto(base+'/'+domain+'-atlas.html',{waitUntil:'domcontentloaded'});assert.equal(first.status(),200);const atlas=page.locator('[data-figure="'+figure+'"]');await atlas.waitFor();await atlas.locator('img').evaluate(i=>i.decode());assert.equal(await page.locator('.technical-atlas').count(),1);assert.match(await atlas.locator('figcaption').textContent(),figure==='TA-22'?/不认证内部电路或端口/:/只传热、不混液/);
 for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await atlas.locator('figure>a').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 249, 242)');await page.evaluate(()=>scrollTo(0,0));const file=domain+'-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});results.views.push({kind:'static',width,theme,file,height:await page.evaluate(()=>document.documentElement.scrollHeight)});}
 await page.setViewportSize({width:360,height:844});const header=await page.locator('#ui-skinbar').boundingBox();assert.ok(header.height<=86);results.header360=header;
 const manifest=JSON.parse(fs.readFileSync(path.join(D,'asset-manifest-v1.json')));for(const name of['下载标注图','下载无字底图']){const wait=page.waitForEvent('download');await atlas.getByRole('link',{name,exact:true}).click();const dl=await wait,p=path.join(out,dl.suggestedFilename());await dl.saveAs(p);const b=fs.readFileSync(p),a=manifest.assets.find(a=>path.basename(a.file)===dl.suggestedFilename());assert.equal(hash(b),a.sha256);assert.equal(b.length,a.bytes);results.downloads.push({name,file:dl.suggestedFilename(),bytes:b.length,sha256:hash(b)});}
 await page.goto(base+'/assets/technical-atlas/'+domain+'-domain-v1.svg');await page.setViewportSize({width:1536,height:1024});await page.evaluate(()=>document.fonts.ready);await page.locator('image').evaluateAll(es=>Promise.all(es.map(e=>new Promise((ok,no)=>{const i=new Image;i.onload=ok;i.onerror=no;i.src=e.getAttribute('href')}))));assert.equal(await page.locator('.callout').count(),6);const texts=await page.locator('text').evaluateAll(es=>es.map(e=>{const b=e.getBBox();return{text:e.textContent,b:{x:b.x,y:b.y,w:b.width,h:b.height}}}));assert.ok(texts.every(t=>t.b.x>=0&&t.b.y>=0&&t.b.x+t.b.w<=1536&&t.b.y+t.b.h<=1024));const file=domain+'-full-svg-1536.png';await page.locator('svg').screenshot({path:path.join(out,file)});results.views.push({kind:'fullSVG',file,texts:texts.length});
 for(const name of[domain+'-atlas','facility-atlas']){const r=await context.request.get(base+'/'+name+'.html',{maxRedirects:0});assert.equal(r.status(),200);const s=await r.text(),urls=[...s.matchAll(/<(?:script|link)[^>]+(?:src|href)="([^"]+)"/g)].map(x=>x[1]);assert.ok(!urls.includes('/assets/site-shell.js'));for(const url of urls){const r=await context.request.get(base+url,{maxRedirects:0});assert.equal(r.status(),200);results.declared_resources.push({page:name,url,status:r.status()})}}
 async function observe(route,marker,replacement){try{const headers={...route.request().headers()};delete headers['if-none-match'];delete headers['if-modified-since'];const r=await route.fetch({headers,maxRedirects:0}),b=await r.body(),s=b.toString('utf8');assert.equal(r.status(),200);assert.ok(b.length);const name=new URL(route.request().url()).pathname,local=name==='/bom3d.html'?'web/pages/bom3d.html':'web/components/part-inspector.js';assert.equal(hash(b),hash(fs.readFileSync(path.join(root,local))),'Actual deployed source identity');results.sources.push({url:route.request().url(),status:r.status(),bytes:b.length,sha256:hash(b),observation_only_injection:true});assert.equal(s.split(marker).length-1,1);await route.fulfill({response:r,body:s.replace(marker,replacement)})}catch(e){results.route_errors.push(e.message);await route.abort('failed')}}
 await page.route(/\/assets\/part-inspector\.js(?:\?[^#]*)?$/,r=>observe(r,'return {canvas: iCv,','return {objectsForTest:()=>iGroup?.children||[],canvas: iCv,'));
 await page.route(/\/bom3d\.html(?:\?[^#]*)?$/,r=>observe(r,'</script>\n</body>','globalThis.__energyTest={THREE,campusAssembly,campusMode,canvas,camera,controls,pickables,PART,RIGHTS,PARTMESH,inspector,sceneView,dimmed,currentPartMeshes,showDossier,disposePage,state:()=>({selectedInstance:campusSelectedInstance,activeDomain,stage:+slider.value})};\n</script>\n</body>'));
 async function settle(){await page.evaluate(async()=>{await document.fonts.ready;await new Promise(a=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(a))))});assert.deepEqual(results.route_errors,[])}
 async function go(q){const r=await page.goto(base+'/bom3d.html'+q,{waitUntil:'domcontentloaded'});assert.equal(r.status(),200);await page.waitForFunction(()=>!!globalThis.__energyTest);await settle()}
 async function close(){await page.locator('#dossier .close').click();await settle()}
 for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await go('?d='+domain);await page.locator('#ui-appearance').selectOption(theme);const panel=page.locator('.ui-viewer-controls');if(!await panel.evaluate(e=>e.open))await panel.locator(':scope>summary').click();const plate=page.locator('.facility-domain-plate[data-figure="'+figure+'"]');assert.equal(await plate.count(),1);await plate.locator('img').evaluate(i=>i.decode());assert.equal(await page.locator('#domainParts .pitem').count(),total);assert.equal(await page.locator('#domainParts .nm').filter({hasText:'本场景未建模'}).count(),missing);assert.match(await page.locator('#walkBtn').textContent(),/非接线\/管线顺序/);await page.locator('#fit-view').click();await settle();if(width===390){await page.screenshot({path:path.join(out,domain+'-domain-controls-'+theme+'.png')});await panel.locator(':scope>summary').click();await page.evaluate(()=>__energyTest.sceneView.fit());await settle()}
  const g=await page.evaluate(domain=>{const v=__energyTest;return{state:v.state(),mesh:v.pickables.length,instances:v.campusAssembly.instances.map(i=>({id:i.id,part:i.part,home:i.home.toArray(),position:i.object.position.toArray()})),domainInstances:v.campusAssembly.instances.filter(i=>v.PART[i.part]?.system===domain).map(i=>({id:i.id,part:i.part})),nonphysical:['dcim','modular-dc',...v.RIGHTS.map(p=>p.id)].map(id=>[id,v.campusAssembly.objectsFor(id).length])}},domain);assert.equal(g.mesh,152);assert.equal(g.instances.length,32);assert.equal(g.domainInstances.length,physical);assert.equal(new Set(g.domainInstances.map(i=>i.part)).size,total-missing);assert.ok(g.nonphysical.every(([id,n])=>n===0));for(const i of g.instances)assert.deepEqual(i.position,i.home);results.domain_geometry=g;const file=domain+'-domain-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,file)});results.views.push({kind:'domain3D',width,theme,file});}
 await page.setViewportSize({width:1280,height:900});await go('?d='+domain);const sysText=fs.readFileSync(path.join(root,'web/components/system-atlas.js'),'utf8'),systemArt=JSON.parse(sysText.slice(sysText.indexOf('{'),sysText.lastIndexOf('}')+1));const ids=await page.locator('#domainParts .pitem').evaluateAll(es=>es.map(e=>e.dataset.part));assert.equal(ids.length,total);
 for(const id of ids){await page.locator('#domainParts .pitem[data-part="'+id+'"]').click();await settle();const a=page.locator('#dossier .technical-atlas');assert.equal(await a.count(),1,id+' independent category artwork');await a.locator('img').evaluate(i=>i.decode());const expected=systemArt[id]?.preview||({'psu':'/assets/technical-atlas/psu-v1-preview.svg','coldplate':'/assets/technical-atlas/coldplate-v1-preview.svg','server-fan':'/assets/technical-atlas/fan-wall-v1-preview.svg'})[id];assert.equal(await a.locator('img').getAttribute('src'),expected);const v=await page.evaluate(()=>{const v=__energyTest,d=document.querySelector('#dossier');return{id:d.dataset.partId,text:d.textContent,clones:v.inspector.objectsForTest().length,inspectorVisible:getComputedStyle(d.querySelector('#inspSlot')).display!=='none',canvasConnected:v.inspector.canvas.isConnected,instances:v.campusAssembly.objectsFor(d.dataset.partId).length,selected:v.state().selectedInstance}});assert.equal(v.id,id);if(v.instances){assert.ok(v.clones>0);assert.equal(v.inspectorVisible,true);assert.equal(v.canvasConnected,true);assert.match(v.text,/内接线、流体拓扑.*未知/)}else{assert.equal(v.inspectorVisible,false);assert.equal(v.canvasConnected,false);assert.equal(v.selected,null);assert.match(v.text,/本次园区未造实体/)}results.categories.push({id,preview:expected,cached_clones:v.clones,visible_clones:v.inspectorVisible&&v.canvasConnected?v.clones:0,inspector_visible:v.inspectorVisible,canvas_connected:v.canvasConnected,instances:v.instances,selected:v.selected});await close()}
 // Explicitly exercise cross-domain background selection and whole context without system-only binding leakage.
 const other=domain==='power'?'chiller':'transformer';await page.evaluate(id=>__energyTest.showDossier(__energyTest.PART[id]),other);assert.equal(await page.locator('#dossier .technical-atlas').count(),0);await close();await page.locator('#campus-whole-dossier').click();assert.equal(await page.locator('#dossier .technical-atlas[data-figure="TA-36"]').count(),1);assert.equal(await page.locator('#dossier .technical-atlas img').getAttribute('src'),'/assets/technical-atlas/shell-v1-preview.svg');assert.equal(await page.evaluate(()=>__energyTest.inspector.objectsForTest().length),152);await close();results.cross_domain_binding_isolated=true;
 await page.locator('#fit-view').click();await settle();const xy=await page.evaluate(part=>{const v=__energyTest,r=v.canvas.getBoundingClientRect(),ray=new v.THREE.Raycaster(),hud=document.querySelector('.hud').getBoundingClientRect(),legend=document.querySelector('.campus-legend').getBoundingClientRect();v.campusAssembly.root.updateMatrixWorld(true);v.camera.updateMatrixWorld(true);for(let y=150;y<legend.top;y+=5)for(let x=Math.max(340,hud.right+5);x<r.right-15;x+=5){ray.setFromCamera(new v.THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),v.camera);const h=ray.intersectObjects(v.pickables,true).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent}return true});if(h?.object.userData.part===part)return{x,y,instance:v.campusAssembly.instanceFor(h.object).id}}throw Error('No visible '+part+' pointer sample')},probe);
 await page.mouse.move(xy.x,xy.y);await page.mouse.click(xy.x,xy.y);await settle();assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),probe);assert.equal(await page.evaluate(()=>__energyTest.state().selectedInstance),xy.instance);assert.ok(await page.evaluate(()=>__energyTest.inspector.objectsForTest().length)>0);results.real_pointer=xy;const dossier=domain+'-instance-dossier.png';await page.screenshot({path:path.join(out,dossier)});results.views.push({kind:'dossier',file:dossier});const wait=page.waitForEvent('download');await page.locator('#atlas-export').click();const dl=await wait,p=path.join(out,domain+'-current.svg');await dl.saveAs(p);const data=fs.readFileSync(p);assert.ok(data.toString().includes(xy.instance));results.current_export={file:path.basename(p),sha256:hash(data),instance:xy.instance};await close();
 const panel=page.locator('.ui-viewer-controls');if(await panel.evaluate(e=>e.open)&&await panel.locator(':scope>summary').isVisible())await panel.locator(':scope>summary').click();await page.evaluate(()=>__energyTest.controls.enableDamping=false);const before=await page.evaluate(()=>__energyTest.camera.position.toArray());await page.mouse.move(850,420);await page.mouse.down();await page.mouse.move(925,465,{steps:12});await page.mouse.up();await settle();const moved=await page.evaluate(()=>__energyTest.camera.position.toArray());assert.ok(Math.hypot(...moved.map((n,k)=>n-before[k]))>.01);await page.setViewportSize({width:1260,height:900});await page.waitForTimeout(500);const after=await page.evaluate(()=>__energyTest.camera.position.toArray());assert.ok(Math.hypot(...after.map((n,k)=>n-moved[k]))<1e-8);results.manual_camera_retained=true;
 if(domain==='thermal'){await go('?d=cooling');assert.equal(await page.locator('[data-figure="TA-23"]').count(),1);results.thermal_alias=true}
 await go('?d=facility');assert.equal(await page.locator('[data-figure="TA-21"]').count(),1);assert.equal(await page.locator('[data-figure="'+figure+'"]').count(),0);await go('?d=control');assert.equal(await page.locator('.facility-domain-plate[data-figure="TA-28"]').count(),1);assert.equal(await page.locator('[data-figure="'+figure+'"]').count(),0);assert.equal(await page.evaluate(()=>__energyTest.campusAssembly.objectsFor('dcim').length),0);
 for(const q of['','?x=70']){await go(q);assert.equal(await page.locator('.facility-domain-plate').count(),0);const file=q?'TA19-linked-default.png':'TA18-linked-default.png';await page.screenshot({path:path.join(out,file)});results.views.push({kind:'old3D',file})}
 await page.goto(base+'/bom.html#ssd');await page.locator('[data-figure="TA-01"]').waitFor();assert.equal(await page.locator('[data-figure="'+figure+'"]').count(),0);await page.goto(base+'/server-plan.html');await page.locator('[data-figure="TA-12"]').waitFor();results.default_scope_isolation=true;
 assert.deepEqual(results.errors,[]);assert.deepEqual(results.route_errors,[]);assert.deepEqual(results.resource_failures,[]);results.status='PASS';console.log(figure+' actual public4static+4domain/fullSVG/dualdownload/'+total+'categories/'+missing+'unmodeled/realpointer/export/manualownership/scope PASS');
 }catch(e){results.status='FAIL';results.failure=e.stack||String(e);throw e}finally{results.finished_at=new Date().toISOString();fs.writeFileSync(path.join(out,domain+'-domain-results.json'),JSON.stringify(results,null,2)+'\n');if(browser)await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
