/* TA21 real public HTTPS checks; never starts or accesses a local product site. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright');
assert.equal(process.env.UI_BASE_URL,'https://inresearch.ai','This task requires the explicitly authorized actual public origin');
const base=process.env.UI_BASE_URL,root=process.env.TA21_SOURCE_ROOT||path.resolve(__dirname,'..'),out=process.env.REVIEW_SCREENSHOTS||'/private/tmp/ta21-public-'+Date.now(),D=path.join(root,'docs/design/technical-atlas/TA-21'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');fs.mkdirSync(out,{recursive:true});
const results={observed_at:new Date().toISOString(),base,views:[],downloads:[],sources:[],declared_resources:[],rights:[],errors:[],route_errors:[]};let browser;
(async()=>{try{browser=await chromium.launch({headless:process.env.UI_HEADED!=='1'});const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true});await context.route('**/*',async r=>{try{const u=new URL(r.request().url());assert.equal(u.origin,base);await r.continue()}catch(e){results.route_errors.push(e.message);await r.abort('blockedbyclient')}});const page=await context.newPage();page.on('pageerror',e=>results.errors.push(e.message));
 const response=await page.goto(base+'/facility-atlas.html',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);const atlas=page.locator('[data-figure="TA-21"]');await atlas.waitFor();await atlas.locator('img').evaluate(i=>i.decode());assert.match(await atlas.locator('figcaption').textContent(),/六类非物理证据入口/);assert.equal(await page.locator('.technical-atlas').count(),1);
 for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await atlas.locator('figure>a').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 249, 242)');await page.evaluate(()=>scrollTo(0,0));const file='facility-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});results.views.push({kind:'static',width,theme,file,height:await page.evaluate(()=>document.documentElement.scrollHeight)});}
 await page.setViewportSize({width:360,height:844});const header=await page.locator('#ui-skinbar').boundingBox();assert.ok(header.height<=86);results.header360=header;
 const m=JSON.parse(fs.readFileSync(path.join(D,'asset-manifest-v1.json')));for(const label of['下载标注图','下载无字底图']){const link=atlas.getByRole('link',{name:label,exact:true}),wait=page.waitForEvent('download');await link.click();const dl=await wait,p=path.join(out,dl.suggestedFilename());await dl.saveAs(p);const b=fs.readFileSync(p),a=m.assets.find(a=>path.basename(a.file)===dl.suggestedFilename());assert.equal(hash(b),a.sha256);results.downloads.push({label,file:dl.suggestedFilename(),bytes:b.length,sha256:hash(b)});}
 await page.goto(base+'/assets/technical-atlas/facility-domain-v1.svg');await page.setViewportSize({width:1536,height:1024});await page.evaluate(()=>document.fonts.ready);await page.locator('image').evaluateAll(es=>Promise.all(es.map(e=>new Promise((resolve,reject)=>{const i=new Image;i.onload=resolve;i.onerror=reject;i.src=e.getAttribute('href')}))));assert.equal(await page.locator('.callout').count(),4);const texts=await page.locator('text').evaluateAll(es=>es.map(e=>{const b=e.getBBox();return{text:e.textContent,b:{x:b.x,y:b.y,width:b.width,height:b.height}}}));assert.ok(texts.every(t=>t.b.x>=0&&t.b.y>=0&&t.b.x+t.b.width<=1536&&t.b.y+t.b.height<=1024));await page.locator('svg').screenshot({path:path.join(out,'facility-full-svg-1536.png')});results.views.push({kind:'fullSVG',file:'facility-full-svg-1536.png',texts:texts.length});
 // Direct200 declared source checks for new page and four old pages with removed redundant modules.
 for(const name of['facility-atlas','server-plan','chip-atlas','rack-atlas','rack-exploded']){const r=await context.request.get(base+'/'+name+'.html',{maxRedirects:0});assert.equal(r.status(),200);const body=await r.text();const urls=[...body.matchAll(/<(?:script|link)[^>]+(?:src|href)="([^"]+)"/g)].map(x=>x[1]);assert.ok(!urls.includes('/assets/site-shell.js'));for(const url of urls){assert.ok(url.startsWith('/assets/'));const r=await context.request.get(base+url,{maxRedirects:0});results.declared_resources.push({page:name,url,status:r.status()});assert.equal(r.status(),200)}}
 async function observe(route,marker,replacement){try{const headers={...route.request().headers()};delete headers['if-none-match'];delete headers['if-modified-since'];const r=await route.fetch({headers,maxRedirects:0}),b=await r.body(),s=b.toString('utf8');assert.equal(r.status(),200);assert.ok(b.length);const name=new URL(route.request().url()).pathname;const local=name==='/bom3d.html'?'web/pages/bom3d.html':'web/components/part-inspector.js';assert.equal(hash(b),hash(fs.readFileSync(path.join(root,local))),'Actual deployed source identity');results.sources.push({url:route.request().url(),bytes:b.length,status:r.status(),sha256:hash(b),observation_only_injection:true});assert.equal(s.split(marker).length-1,1);await route.fulfill({response:r,body:s.replace(marker,replacement)})}catch(e){results.route_errors.push(e.message);await route.abort('failed')}}
 await page.route(/\/assets\/part-inspector\.js(?:\?[^#]*)?$/,r=>observe(r,'return {canvas: iCv,','return {objectsForTest:()=>iGroup?.children||[],canvas: iCv,'));
 const exposure='globalThis.__facilityTest={THREE,campusAssembly,campusMode,canvas,camera,controls,pickables,PART,RIGHTS,PARTMESH,inspector,sceneView,dimmed,currentPartMeshes,disposePage,state:()=>({selectedInstance:campusSelectedInstance,activeDomain,stage:+slider.value})};\n</script>\n</body>';
 await page.route(/\/bom3d\.html(?:\?[^#]*)?$/,r=>observe(r,'</script>\n</body>',exposure));
 async function settle(){await page.evaluate(async()=>{await document.fonts.ready;await new Promise(a=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(a))))});assert.deepEqual(results.route_errors,[])}
 async function go(q){const r=await page.goto(base+'/bom3d.html'+q,{waitUntil:'domcontentloaded'});assert.equal(r.status(),200);await page.waitForFunction(()=>!!globalThis.__facilityTest);await settle()}
 async function closeDossier(){await page.locator('#dossier .close').click();await settle()}
 for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await go('?d=facility');await page.locator('#ui-appearance').selectOption(theme);const panel=page.locator('.ui-viewer-controls');if(!await panel.evaluate(e=>e.open))await panel.locator(':scope>summary').click();await page.locator('.facility-domain-plate img').evaluate(i=>i.decode());assert.equal(await page.locator('.facility-domain-plate[data-figure="TA-21"]').count(),1);assert.equal(await page.locator('#domainParts .pitem').count(),11);assert.equal(await page.locator('#domainParts .nm').filter({hasText:'非物理权利'}).count(),6);assert.equal(await page.locator('#domainParts .nm').filter({hasText:'本场景未建模'}).count(),2);assert.equal(await page.locator('#domainParts .nm').filter({hasText:'交付模板'}).count(),1);await page.locator('#fit-view').click();await settle();assert.equal(await page.locator('#explode').inputValue(),'0');if(width===390){await page.screenshot({path:path.join(out,'facility-domain-controls-'+theme+'.png')});await panel.locator(':scope>summary').click();await page.evaluate(()=>__facilityTest.sceneView.fit());await settle();}const geometry=await page.evaluate(()=>{const v=__facilityTest;return {state:v.state(),mesh:v.pickables.length,instances:v.campusAssembly.instances.map(i=>({id:i.id,part:i.part,home:i.home.toArray(),position:i.object.position.toArray()})),missing:['fire','security','dcim','modular-dc',...v.RIGHTS.map(p=>p.id)].map(p=>[p,v.campusAssembly.objectsFor(p).length])}});assert.equal(geometry.mesh,152);assert.equal(geometry.instances.length,32);for(const i of geometry.instances)assert.deepEqual(i.position,i.home);assert.ok(geometry.missing.every(([id,n])=>n===0));results.domain_geometry=geometry;const file='facility-domain-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,file)});results.views.push({kind:'domain3D',width,theme,file});}
 await page.setViewportSize({width:1280,height:900});await go('?d=campus');assert.equal(await page.locator('.facility-domain-plate').count(),1);results.facility_alias=true;
 for(const [id,canonical]of[['land','land'],['water','water-rights'],['grid','grid'],['fuel-supply','gas-supply'],['network-access','network-access'],['permits','permits']]){const actual=await page.evaluate(c=>__facilityTest.RIGHTS.find(p=>p.site_right_id===c).id,canonical);await page.locator('#domainParts .pitem[data-part="'+actual+'"]').click();await settle();const value=await page.evaluate(()=>{const v=__facilityTest,d=document.querySelector('#dossier');return {part:d.dataset.partId,text:d.textContent,links:[...d.querySelectorAll('a')].map(a=>a.href),clones:v.inspector.objectsForTest().length,selectedMeshes:v.currentPartMeshes(d.dataset.partId)?.length||0,state:v.state()}});assert.equal(value.part,actual);assert.match(value.text,/非物理/);assert.equal(value.clones,0);assert.equal(value.selectedMeshes,0);assert.ok(value.links.some(u=>{try{return new URL(u).searchParams.get('id')==='site:'+canonical}catch{return false}}));results.rights.push({id,canonical,...value});await closeDossier();}
 for(const[id,figure]of[['fire','TA-37'],['security','TA-38']]){await page.locator('#domainParts .pitem[data-part="'+id+'"]').click();await settle();assert.match(await page.locator('#dossier').textContent(),/本次园区未造实体/);await page.locator('#dossier [data-figure="'+figure+'"] img').evaluate(i=>i.decode());assert.equal(await page.evaluate(()=>__facilityTest.inspector.objectsForTest().length),0);await closeDossier()}
 await page.locator('#domainParts .pitem[data-part="modular-dc"]').click();assert.match(await page.locator('#dossier').textContent(),/配置与交付模板，不新增物理设备/);await closeDossier();
 // Real pointer sample on an actual visible rack; no direct synthetic selection.
 await page.locator('#fit-view').click();await settle();const xy=await page.evaluate(()=>{const v=__facilityTest,r=v.canvas.getBoundingClientRect(),ray=new v.THREE.Raycaster(),hud=document.querySelector('.hud').getBoundingClientRect(),legend=document.querySelector('.campus-legend').getBoundingClientRect();v.campusAssembly.root.updateMatrixWorld(true);v.camera.updateMatrixWorld(true);for(let y=150;y<legend.top;y+=5)for(let x=Math.max(340,hud.right+5);x<r.right-15;x+=5){ray.setFromCamera(new v.THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),v.camera);const h=ray.intersectObjects(v.pickables,true).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent}return true});if(h?.object.userData.part==='rack-frame')return{x,y,instance:v.campusAssembly.instanceFor(h.object).id}}throw Error('No visiblerackpointer sample')});await page.mouse.move(xy.x,xy.y);await page.mouse.click(xy.x,xy.y);await settle();assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),'rack-frame');assert.equal(await page.evaluate(()=>__facilityTest.state().selectedInstance),xy.instance);assert.ok(await page.evaluate(()=>__facilityTest.inspector.objectsForTest().length)>0);results.real_pointer=xy;await page.screenshot({path:path.join(out,'facility-rack-instance-dossier.png')});results.views.push({kind:'dossier',file:'facility-rack-instance-dossier.png'});const wait=page.waitForEvent('download');await page.locator('#atlas-export').click();const exportDl=await wait;const exportPath=path.join(out,'facility-rack-current.svg');await exportDl.saveAs(exportPath);const exportBody=fs.readFileSync(exportPath,'utf8');assert.ok(exportBody.includes(xy.instance));results.current_export={file:path.basename(exportPath),sha256:hash(Buffer.from(exportBody)),instance:xy.instance};await closeDossier();
 const panel=page.locator('.ui-viewer-controls');if(await panel.evaluate(e=>e.open)&&await panel.locator(':scope>summary').isVisible())await panel.locator(':scope>summary').click();await page.evaluate(()=>{const v=__facilityTest;v.controls.enableDamping=false});const before=await page.evaluate(()=>__facilityTest.camera.position.toArray());await page.mouse.move(850,420);await page.mouse.down();await page.mouse.move(925,465,{steps:12});await page.mouse.up();await settle();const moved=await page.evaluate(()=>__facilityTest.camera.position.toArray());assert.ok(Math.hypot(...moved.map((n,k)=>n-before[k]))>.01);await page.setViewportSize({width:1260,height:900});await page.waitForTimeout(500);const resized=await page.evaluate(()=>__facilityTest.camera.position.toArray());assert.ok(Math.hypot(...moved.map((n,k)=>n-resized[k]))<1e-8);results.manual_camera_retained=true;
 for(const q of['','?x=70']){await go(q);assert.equal(await page.locator('.facility-domain-plate').count(),0);await page.screenshot({path:path.join(out,q?'TA19-linked-default.png':'TA18-linked-default.png')});results.views.push({kind:'old3D',file:q?'TA19-linked-default.png':'TA18-linked-default.png'})}
 await go('?d=control');assert.equal(await page.locator('.facility-domain-plate').count(),0);assert.equal(await page.evaluate(()=>__facilityTest.campusAssembly.objectsFor('dcim').length),0);results.control_software_retained=true;
 await page.goto(base+'/server-plan.html');await page.locator('[data-figure="TA-12"]').waitFor();assert.equal(await page.locator('[data-figure="TA-21"]').count(),0);await page.goto(base+'/bom.html#ssd');await page.locator('[data-figure="TA-01"]').waitFor();assert.equal(await page.locator('[data-figure="TA-21"]').count(),0);results.default_scope_isolation=true;
 assert.deepEqual(results.errors,[]);assert.deepEqual(results.route_errors,[]);results.status='PASS';console.log('TA21 actual public:4static+4domain views/fullSVG/dualdownload/directresources/sixnonphysical/2unmodeled/archetype/realrackpointer/export/manualownership/oldscope PASS');
}catch(e){results.status='FAIL';results.failure=e.stack||String(e);throw e}finally{results.finished_at=new Date().toISOString();fs.writeFileSync(path.join(out,'facility-domain-results.json'),JSON.stringify(results,null,2)+'\n');if(browser)await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
