const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const cell=(text,colspan=1)=>({text,colspan,rowspan:1,header:false});
  const product={id:'nvidia-aaaaaaaaaaaaaaaaaaaa',name:'NVIDIA H200',category:'Data Center',kind:'named_product',observed_at:'2026-09-27',source_url:'https://www.nvidia.com/en-us/data-center/h200/',source_sha256:'a'.repeat(64),attachments:[],tables:[{index:1,section:'Specifications',notes:'* Sparse, per GPU',rows:[[cell(''),cell('SXM'),cell('NVL')],[cell('Memory'),cell('141 GB',2)]]}]};
  product.navigation={group:'datacenter',family:'accelerators',family_label:'GPU / CPU / 超级芯片',role:'catalog'};
  const groups=[['datacenter','数据中心与网络'],['consumer','游戏与消费产品'],['professional','专业图形与工作站'],['embedded','嵌入式与汽车'],['software','软件与云服务']].map(([id,label])=>({id,label}));
  const gaming={...product,id:'gaming',name:'GeForce RTX 5090',navigation:{group:'consumer',family:'geforce-50',family_label:'GeForce RTX 50 系列',role:'catalog'}};
  const auxiliary={...product,id:'training',name:'NVIDIA Training',navigation:{group:'',family:'',family_label:'待归类',role:'auxiliary'}};
  const more=Array.from({length:17},(_,i)=>({...product,id:'extra'+i,name:'ZZZ GPU '+i}));
  await page.route('**/api/product-catalog/nvidia',r=>r.fulfill({json:{available:true,generated_at:'2026-09-27',coverage:{directory_entries:48,entity_counts:{named_product:1},with_spec_tables:1,pending_pages:4,failed_pages:0,limitations:['Not exhaustive']},navigation:{groups},products:[product,gaming,auxiliary,...more]}}));
  await page.goto(process.env.UI_BASE_URL+'/product-catalog.html');
  await page.getByRole('heading',{name:'NVIDIA H200',exact:true}).waitFor();
  assert.match(await page.locator('#detail').innerText(),/141 GB/);
  assert.equal(await page.locator('#detail td[colspan="2"]').innerText(),'141 GB');
  assert.match(await page.locator('#detail').innerText(),/Sparse/);
  assert.equal(await page.locator('#groups button').count(),5);
  assert.equal(await page.locator('.product').count(),15);
  assert.ok(!(await page.locator('#products').innerText()).includes('Training'));
  await page.locator('#next').click();assert.equal(await page.locator('.product').count(),3);
  await page.locator('#previous').click();
  await page.locator('[data-group="consumer"]').click();
  assert.match(await page.locator('#breadcrumb').innerText(),/游戏与消费产品.*GeForce/);
  assert.equal(await page.locator('.product').count(),1);
  assert.match(await page.locator('#export-products').getAttribute('href'),/group=consumer.*family=geforce-50/);
  await page.locator('#auxiliary').click();assert.match(await page.locator('#products').innerText(),/Training/);
  await page.locator('[data-group="datacenter"]').click();
  await page.locator('#compare').click();assert.equal(await page.locator('#comparison').isVisible(),true);
  await page.locator('#query').fill('unmatched');assert.match(await page.locator('#matches').innerText(),/^0/);
  await page.locator('#query').fill('H200');assert.match(await page.locator('#export-specs').getAttribute('href'),/q=h200/);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.equal(await page.locator('.product').first().evaluate(el=>getComputedStyle(el).borderRadius),'0px');
  await page.unroute('**/api/product-catalog/nvidia');
  await page.route('**/api/product-catalog/nvidia',r=>r.fulfill({status:503,body:'unavailable'}));
  await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('暂时不可用'));
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
