const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const cell=(text,colspan=1)=>({text,colspan,rowspan:1,header:false});
  const product={id:'nvidia-aaaaaaaaaaaaaaaaaaaa',name:'NVIDIA H200',category:'Data Center',kind:'named_product',observed_at:'2026-09-27',source_url:'https://www.nvidia.com/en-us/data-center/h200/',source_sha256:'a'.repeat(64),official_pages:[{url:'https://www.nvidia.cn/data-center/h200/',sha256:'b'.repeat(64)}],website_sitemap:{matched:true,roles:['en_us']},attachments:[],tables:[{index:1,section:'Specifications',notes:'* Sparse, per GPU',source_refs:[{url:'https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/h200.pdf',sha256:'c'.repeat(64)}],rows:[[cell(''),cell('SXM'),cell('NVL')],[cell('Memory'),cell('141 GB',2)]]}]};
  product.navigation={group:'datacenter',family:'accelerators',family_label:'GPU / CPU / 超级芯片',role:'catalog'};
  const groups=[['datacenter','数据中心与网络'],['consumer','游戏与消费产品'],['professional','专业图形与工作站'],['embedded','嵌入式与汽车'],['software','软件与云服务']].map(([id,label])=>({id,label}));
  const gaming={...product,id:'gaming',name:'GeForce RTX 5090',navigation:{group:'consumer',family:'geforce-50',family_label:'GeForce RTX 50 系列',role:'catalog'}};
  const auxiliary={...product,id:'training',name:'NVIDIA Training',navigation:{group:'',family:'',family_label:'待归类',role:'auxiliary'}};
  const unavailable={...product,id:'gtx-660-oem',name:'GeForce GTX 660 OEM',tables:[],extraction_status:'official_specification_source_unavailable',navigation:{group:'',family:'',family_label:'待归类',role:'auxiliary'}};
  const unpublished={...product,id:'titan-z',name:'GeForce GTX TITAN Z',tables:[],extraction_status:'official_specification_not_published_on_observed_page',navigation:{group:'',family:'',family_label:'待归类',role:'auxiliary'}};
  const more=Array.from({length:17},(_,i)=>({...product,id:'extra'+i,name:'ZZZ GPU '+i}));
  await page.route('**/api/product-catalog/nvidia',r=>r.fulfill({json:{available:true,generated_at:'2026-09-27',coverage:{directory_entries:48,entity_counts:{named_product:22},with_spec_tables:20,pending_pages:4,failed_pages:0,unavailable_pages:35,policy_blocked_pages:2,website_sitemap:{candidate_urls:7062,product_path_candidates:427,product_path_observed:423,matched_catalog_sources:1},limitations:['Not exhaustive']},navigation:{groups},products:[product,gaming,auxiliary,unavailable,unpublished,...more]}}));
  await page.goto(process.env.UI_BASE_URL+'/product-catalog.html');
  await page.getByRole('heading',{name:'NVIDIA H200',exact:true}).waitFor();
  await page.locator('#detail details summary').first().click();
  assert.match(await page.locator('#detail').innerText(),/141 GB/);
  assert.equal(await page.locator('#detail td[colspan="2"]').innerText(),'141 GB');
  assert.match(await page.locator('#detail').innerText(),/Sparse/);
  assert.match(await page.locator('#detail').innerText(),/表格来源：查看原始附件/);
  assert.equal(await page.locator('#detail').getByRole('link',{name:'查看原始附件'}).getAttribute('href'),'https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/h200.pdf');
  await page.locator('#detail details').nth(1).locator('summary').click();
  assert.match(await page.locator('#detail details').nth(1).locator('a').getAttribute('href'),/nvidia\.cn/);
  assert.match(await page.locator('#detail').innerText(),/en_us/);
  assert.match(await page.locator('#status').innerText(),/官方 sitemap 候选 7062/);
  await page.locator('main details').first().locator('summary').click();
  assert.match(await page.locator('#status').innerText(),/具体型号规格 20 \/ 22/);
  assert.match(await page.locator('#metrics').innerText(),/20 \/ 22[\s\S]*具体型号规格覆盖[\s\S]*2[\s\S]*官网明确规格缺口/);
  assert.match(await page.locator('#metrics').innerText(),/423 \/ 427[\s\S]*已核对产品 URL/);
  assert.match(await page.locator('#metrics').innerText(),/0[\s\S]*访问失败（可重试）[\s\S]*35[\s\S]*官网已删除旧页[\s\S]*2[\s\S]*策略阻止跳转/);
  assert.match(await page.locator('#export-map').getAttribute('href'),/export=map/);
  assert.equal(await page.locator('#groups button').count(),5);
  assert.equal(await page.locator('.product').count(),15);
  assert.ok(!(await page.locator('#products').innerText()).includes('Training'));
  await page.locator('#next').click();assert.equal(await page.locator('.product').count(),3);
  await page.locator('#previous').click();
  await page.locator('[data-group="consumer"]').click();
  assert.match(await page.locator('#breadcrumb').innerText(),/游戏与消费产品.*GeForce/);
  assert.equal(await page.locator('.product').count(),1);
  assert.match(await page.locator('#export-products').getAttribute('href'),/group=consumer.*family=geforce-50/);
  await page.locator('#auxiliary').click();assert.match(await page.locator('#products').innerText(),/Training/);
  await page.getByRole('button',{name:/GeForce GTX 660 OEM/}).click();
  assert.match(await page.locator('#detail').innerText(),/官网规格来源不可用[\s\S]*官网型号专属规格页已删除或不可用/);
  await page.getByRole('button',{name:/GeForce GTX TITAN Z/}).click();
  assert.match(await page.locator('#detail').innerText(),/官网未发布型号规格[\s\S]*未发布型号专属规格表或附件/);
  await page.locator('[data-group="datacenter"]').click();
  await page.locator('#compare').click();assert.equal(await page.locator('#comparison').isVisible(),true);
  await page.locator('#query').fill('unmatched');assert.match(await page.locator('#matches').innerText(),/^0/);
  await page.locator('#query').fill('H200');assert.match(await page.locator('#export-specs').getAttribute('href'),/q=h200/);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.equal(await page.locator('.product').first().evaluate(el=>getComputedStyle(el).borderRadius),'0px');
  await page.unroute('**/api/product-catalog/nvidia');
  await page.route('**/api/product-catalog/nvidia',r=>r.fulfill({status:503,body:'unavailable'}));
  await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('暂时不可用'));
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
