/* TA13 actual procedural overview; old exploded and adopted-model contracts remain separate. */
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce'}),errors=[],results=[],modelRequests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/api\/model-assets|assets\/panels\//.test(r.url()))modelRequests.push(r.url());});
  await page.route(/\/assets\/part-inspector\.js(?:\?[^#]*)?$/,async r=>{const response=await r.fetch(),s=await response.text(),body=s.replace('return {canvas: iCv,','return {objectsForTest:()=>iGroup?.children||[],rotationForTest:()=>({x:iRotX,y:iRotY}),canvas: iCv,');assert.notEqual(body,s);await r.fulfill({response,body});});
  await page.route(/\/rack3d\.html/,async r=>{const response=await r.fetch(),s=await response.text(),body=s.replace('</script>\n</body>','globalThis.__rackTest={rack,rackAssembly,rackOverviewMode,serverMode,pickables,PARTMESH,inspector,camera,controls,scene,canvas,sceneView,disposePage,animated,renderer,composer,currentPartMeshes,sceneModels};\n</script>\n</body>');assert.notEqual(body,s);await r.fulfill({response,body});});
  const screenshot=async name=>{if(process.env.REVIEW_SCREENSHOTS)await page.screenshot({path:process.env.REVIEW_SCREENSHOTS+'/'+name+'.png'});};
  const openControls=async()=>{if(!await page.locator('details[data-responsive-panel]').evaluate(e=>e.open))await page.getByLabel('展开或收起场景控制').click();};
  async function fit(label){
   await openControls();await page.locator('#fit-view').click();
   const r=await page.evaluate(async()=>{const THREE=await import('three'),v=__rackTest;v.scene.updateMatrixWorld(true);v.camera.updateMatrixWorld();let count=0,maxX=0,maxY=0;
    for(const m of v.pickables){let visible=true;for(let p=m;p;p=p.parent)visible&&=p.visible;if(!visible)continue;m.geometry.computeBoundingBox();const b=m.geometry.boundingBox;
     for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const p=new THREE.Vector3(x,y,z).applyMatrix4(m.matrixWorld).project(v.camera);maxX=Math.max(maxX,Math.abs(p.x));maxY=Math.max(maxY,Math.abs(p.y));count++;}}
    const rect=v.canvas.getBoundingClientRect();return {count,maxX,maxY,width:rect.width,height:rect.height,aspect:v.camera.aspect};});
   assert.ok(r.count>0&&r.maxX<=1&&r.maxY<=1,label+' clipped '+JSON.stringify(r));assert.ok(Math.abs(r.aspect-r.width/r.height)<.005);results.push({label,...r});
  }
  await page.goto(process.env.UI_BASE_URL+'/rack3d.html?x=0',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!globalThis.__rackTest);
  assert.equal(await page.evaluate(()=>__rackTest.rackOverviewMode),true);assert.equal(await page.evaluate(()=>__rackTest.serverMode),false);assert.equal(await page.locator('#explode').getAttribute('aria-label'),'整柜分区观察');
  const structure=await page.evaluate(()=>{const v=__rackTest,a=v.rackAssembly,g=a.groups,all=[];v.rack.traverse(o=>{if(o.isMesh)all.push(o)});
   const names=n=>all.filter(o=>o.name===n);return {root:v.rack.name,meshes:all.length,picks:v.pickables.length,distinctPicks:new Set(v.pickables).size,
    posts:g.frame.children.filter(o=>o.name==='frame-post').length,rails:names('mounting-rail').length,railHoles:names('mounting-rail').map(o=>o.geometry.parameters.shapes.holes.length),
    feet:names('adjustable-foot').length,compute:g.servers.children.length,drives:g.servers.children.map(g=>g.children.filter(o=>o.name.startsWith('drive-carrier-')).length),
    power:g.power.children.length,modules:g.power.children.map(g=>g.children.filter(o=>o.name.startsWith('psu-module-')).length),switches:g.network.children.length,
    outerSlides:names('outer-slide-rail').length,innerSlides:names('inner-slide-rail').length,brackets:names('rail-end-bracket').length,
    actualPerforations:names('perforated-drive-front').every(o=>o.geometry.parameters.shapes.holes.length===18),
    categories:[...new Set(v.pickables.map(o=>o.userData.part))].sort(),models:v.sceneModels.objects().length};});
  assert.equal(structure.posts,4);assert.equal(structure.rails,4);assert.ok(structure.railHoles.every(n=>n===84));assert.equal(structure.feet,4);assert.equal(structure.compute,8);assert.ok(structure.drives.every(n=>n===8));assert.equal(structure.power,2);assert.ok(structure.modules.every(n=>n===6));assert.equal(structure.switches,2);
  assert.equal(structure.outerSlides,24);assert.equal(structure.innerSlides,24);assert.equal(structure.brackets,48);assert.equal(structure.actualPerforations,true);assert.equal(structure.meshes,structure.picks);assert.equal(structure.distinctPicks,structure.picks);assert.equal(structure.models,0);assert.deepEqual(structure.categories,['network-switch','power-shelf','rack-frame','server']);assert.deepEqual(modelRequests,[]);results.push({label:'derived actual structure and registry ownership',...structure});
  await page.evaluate(()=>{const all=[];__rackTest.rack.traverse(o=>all.push([o.uuid,o.position.toArray()]));globalThis.__rackHomes=JSON.stringify(all);});
  for(const [stage,category] of [[0,'all'],[25,'power'],[50,'servers'],[70,'network'],[90,'service']]){
   await page.locator('#explode').evaluate((e,x)=>{e.value=x;e.dispatchEvent(new Event('input',{bubbles:true}));},stage);
   const r=await page.evaluate(()=>{const a=__rackTest.rackAssembly,all=[];__rackTest.rack.traverse(o=>all.push([o.uuid,o.position.toArray()]));return {visible:Object.entries(a.groups).filter(([k,g])=>g.visible).map(([k])=>k),sameHomes:JSON.stringify(all)===__rackHomes};});
   assert.equal(r.sameHomes,true);for(const k of ['servers','power','network','service'])assert.equal(r.visible.includes(k),category==='all'||category===k);await fit('focus'+stage);results.push({label:'focus only '+stage,...r});
  }
  await page.locator('#explode').evaluate(e=>{e.value=0;e.dispatchEvent(new Event('input',{bubbles:true}));});
  for(const width of [1280,390])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.locator('#ui-appearance').selectOption(theme);await fit('whole '+width+' '+theme);if(width===390)await page.getByLabel('展开或收起场景控制').click();await screenshot('rack-whole-'+width+'-'+theme);
  }
  await page.setViewportSize({width:1280,height:900});await openControls();await page.locator('#ui-appearance').selectOption('light');await fit('dossier');
  await page.locator('#rack-overview-dossier').click();await page.locator('#dossier canvas').waitFor();
  assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),'rack-frame');assert.equal(await page.locator('#dossier .technical-atlas').getAttribute('data-figure'),'TA-13');assert.match(await page.locator('#dossier').textContent(),/研究链接仍指向机柜类别.*不代表本示例/);assert.doesNotMatch(await page.locator('#dossier').textContent(),/5-10kW|GB200 NVL72/);
  const whole=await page.evaluate(()=>({count:__rackTest.inspector.objectsForTest().length,selected:__rackTest.currentPartMeshes('rack-frame').length,rotation:__rackTest.inspector.rotationForTest()}));assert.equal(whole.count,structure.meshes);assert.equal(whole.selected,structure.meshes);assert.deepEqual(whole.rotation,{x:.2,y:-.55});results.push({label:'whole dossier owns every actual installed mesh',...whole});
  await page.locator('#dossier canvas').scrollIntoViewIfNeeded();await screenshot('rack-complete-dossier');
  const ic=await page.locator('#dossier canvas').boundingBox();await page.mouse.move(ic.x+20,ic.y+20);await page.mouse.down();await page.mouse.move(ic.x+75,ic.y+45,{steps:3});await page.mouse.up();assert.notDeepEqual(await page.evaluate(()=>__rackTest.inspector.rotationForTest()),whole.rotation);
  await page.getByRole('button',{name:'关闭部件档案'}).click();
  // Unknown copper/pipe accessories must not acquire rectifier/manifold facts.
  for(const name of ['unconnected-copper-bar','unconnected-pipe-accessory']){
   const point=await page.evaluate(async name=>{const THREE=await import('three'),v=__rackTest,m=v.rack.getObjectByName(name),rect=v.canvas.getBoundingClientRect();m.updateWorldMatrix(true,false);m.geometry.computeBoundingBox();const p=m.geometry.boundingBox.getCenter(new THREE.Vector3()).applyMatrix4(m.matrixWorld).project(v.camera);return{x:rect.left+(p.x+1)*rect.width/2,y:rect.top+(1-p.y)*rect.height/2,part:m.userData.part};},name);assert.equal(point.part,'rack-frame');await page.mouse.move(point.x,point.y);await page.locator('#tip3d').waitFor({state:'visible'});assert.match(await page.locator('#tip3d').textContent(),/可选服务附件.*连接未知/);await page.mouse.click(point.x,point.y);await page.locator('#dossier canvas').waitFor();assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),'rack-frame');assert.match(await page.locator('#dossier h2').textContent(),/整柜上下文/);
   const pending=page.waitForEvent('download');await page.locator('#atlas-export').click();const d=await pending;assert.equal(await d.failure(),null);const raw=fs.readFileSync(await d.path(),'utf8'),id=await page.evaluate(raw=>JSON.parse(new DOMParser().parseFromString(raw,'image/svg+xml').querySelector('metadata').textContent).object_id,raw);assert.equal(id,'part:rack-frame');results.push({label:'actual unknown service accessory pick/export '+name,object_id:id});await page.getByRole('button',{name:'关闭部件档案'}).click();
  }
  // Actual visible mesh raycast, followed by an ordinary pointer gesture.
  for(const part of ['server','power-shelf','network-switch']){
   const point=await page.evaluate(async part=>{const THREE=await import('three'),v=__rackTest,rect=v.canvas.getBoundingClientRect(),ray=new THREE.Raycaster();v.scene.updateMatrixWorld(true);v.camera.updateMatrixWorld();for(const m of v.pickables.filter(m=>m.userData.part===part)){m.geometry.computeBoundingBox();const c=m.geometry.boundingBox.getCenter(new THREE.Vector3()).applyMatrix4(m.matrixWorld).project(v.camera);if(Math.abs(c.x)>.95||Math.abs(c.y)>.95)continue;const x=rect.left+(c.x+1)*rect.width/2,y=rect.top+(1-c.y)*rect.height/2;if(document.elementFromPoint(x,y)!==v.canvas)continue;ray.setFromCamera(new THREE.Vector2(c.x,c.y),v.camera);if(ray.intersectObjects(v.pickables,false)[0]?.object.userData.part===part)return {x,y};}return null;},part);
   assert.ok(point,'no real pick '+part);await page.mouse.click(point.x,point.y);await page.locator('#dossier canvas').waitFor();assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),part);
   const isolated=await page.evaluate(part=>({count:__rackTest.inspector.objectsForTest().length,category:__rackTest.currentPartMeshes(part).every(o=>o.userData.part===part)}),part);assert.ok(isolated.count>0&&isolated.count<structure.meshes);assert.equal(isolated.category,true);
   const pending=page.waitForEvent('download');await page.locator('#atlas-export').click();const download=await pending;assert.equal(await download.failure(),null);const raw=fs.readFileSync(await download.path(),'utf8'),exported=await page.evaluate(raw=>{const d=new DOMParser().parseFromString(raw,'image/svg+xml');if(d.querySelector('parsererror'))throw Error('invalid current SVG');return {metadata:JSON.parse(d.querySelector('metadata').textContent),labels:d.querySelectorAll('#editable-labels text[stroke]').length,pixels:[__rackTest.canvas.width,__rackTest.canvas.height]};},raw);
   assert.equal(exported.metadata.object_id,'part:'+part);assert.equal(exported.metadata.title,'通用机柜整柜结构图册');assert.deepEqual(exported.metadata.pixels,exported.pixels);assert.ok(exported.labels>=2);results.push({label:'actual single instance pick and export '+part,...isolated,...exported});await page.getByRole('button',{name:'关闭部件档案'}).click();
  }
  const cb=await page.locator('#c').boundingBox();await page.mouse.move(cb.x+cb.width*.55,cb.y+cb.height*.45);await page.mouse.down();await page.mouse.move(cb.x+cb.width*.62,cb.y+cb.height*.48,{steps:4});await page.mouse.up();await page.evaluate(()=>{__rackTest.controls.enableDamping=false;__rackTest.controls.update();});
  const owned=await page.evaluate(()=>({p:__rackTest.camera.position.toArray(),t:__rackTest.controls.target.toArray()}));await page.setViewportSize({width:1000,height:800});await page.evaluate(async()=>{await __rackTest.sceneModels.reload();__rackTest.sceneView.refresh();});const now=await page.evaluate(()=>({p:__rackTest.camera.position.toArray(),t:__rackTest.controls.target.toArray()}));for(const k of ['p','t'])now[k].forEach((n,i)=>assert.ok(Math.abs(n-owned[k][i])<.005,'user camera stolen'));
  const released=await page.evaluate(async()=>{const v=__rackTest,geo=new Set(),mat=new Set();v.rack.traverse(o=>{if(o.isMesh){geo.add(o.geometry);[].concat(o.material).forEach(m=>mat.add(m));}});let geometries=0,materials=0,renders=0;geo.forEach(g=>g.addEventListener('dispose',()=>geometries++));mat.forEach(m=>m.addEventListener('dispose',()=>materials++));const render=v.composer.render.bind(v.composer);v.composer.render=(...args)=>{renders++;return render(...args);};v.disposePage();v.disposePage();const at=renders;await new Promise(r=>setTimeout(r,80));return {geometryCount:geo.size,materialCount:mat.size,geometries,materials,rendersAfter:renders-at,parent:!!v.rack.parent,picks:v.pickables.length,labels:document.querySelectorAll('.atlas-scene-labels').length};});assert.equal(released.geometries,released.geometryCount);assert.equal(released.materials,released.materialCount);assert.equal(released.rendersAfter,0);assert.equal(released.parent,false);assert.equal(released.picks,0);assert.equal(released.labels,0);results.push({label:'exact once resource release',...released});
  for(const [path,overview,server] of [['/rack3d.html',true,false],['/rack3d.html?x=35',false,false],['/rack3d.html?x=90',false,false],['/rack3d.html?x=55',false,true],['/rack3d.html?node=part:gpu',false,false]]){
   await page.goto(process.env.UI_BASE_URL+path,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!globalThis.__rackTest);assert.equal(await page.evaluate(()=>__rackTest.rackOverviewMode),overview);assert.equal(await page.evaluate(()=>__rackTest.serverMode),server);assert.ok(await page.evaluate(()=>__rackTest.pickables.length>0));
  }
  await page.goto(process.env.UI_BASE_URL+'/rack3d.html?view=rack&node=part:rack-frame',{waitUntil:'domcontentloaded'});await page.locator('#dossier canvas').waitFor();assert.equal(await page.evaluate(()=>__rackTest.inspector.objectsForTest().length),structure.meshes);assert.equal(await page.locator('#dossier .technical-atlas').getAttribute('data-figure'),'TA-13');assert.match(await page.locator('#dossier').textContent(),/研究链接仍指向机柜类别.*不代表本示例/);assert.doesNotMatch(await page.locator('#dossier').textContent(),/5-10kW|GB200 NVL72/);results.push({label:'explicit rack-frame overview deep link includes whole installed assembly',count:structure.meshes});
  assert.deepEqual(errors,[]);if(process.env.REVIEW_SCREENSHOTS)fs.writeFileSync(process.env.REVIEW_SCREENSHOTS+'/rack-assembly-results.json',JSON.stringify({observed_at:new Date().toISOString(),results,page_errors:errors},null,2)+'\n');console.log('PASS TA13 actual rack structure, cutaway, focus unchanged homes, true instance picks/export, complete inspector, desktop/phone themes, user camera, release and retained legacy');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
