/* True orthographic formal-native plan, independent reader entry and full downloads. */
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.join(__dirname,'..'),base=process.env.UI_BASE_URL;
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const output=process.env.TA12_AUDIT_DIR;let results={observed_at:new Date().toISOString(),base,views:[],downloads:[],page_errors:[]};if(output)fs.mkdirSync(output,{recursive:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true});page.on('pageerror',e=>results.page_errors.push(e.message));
 await page.goto(base+'/server-plan.html',{waitUntil:'domcontentloaded'});const atlas=page.locator('.technical-atlas[data-figure="TA-12"]');await atlas.waitFor();await atlas.locator('img').evaluate(img=>img.decode());
 assert.equal(await page.locator('.technical-atlas').count(),1);assert.equal(await atlas.locator('img').getAttribute('src'),'/assets/technical-atlas/server-plan-v1-preview.svg');assert.match(await atlas.locator('figcaption').textContent(),/上层四盘可见、下层四盘遮挡/);assert.match(await atlas.locator('figcaption').textContent(),/示例顶罩.*非CAD、非实际尺寸/);
 assert.equal(await atlas.locator('[data-related-figure="TA-11"]').getAttribute('href'),'/bom.html#server');assert.match(await atlas.locator('[data-related-figure="TA-11-3D"]').getAttribute('href'),/view=server.*x=55.*part:server/);
 for(const width of [1280,390])for(const theme of ['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);await atlas.locator('img').scrollIntoViewIfNeeded();assert.ok(await atlas.locator('img').evaluate(img=>img.complete&&img.naturalWidth===1536&&img.naturalHeight===1024));assert.equal(await atlas.locator('figure>a').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(250, 249, 242)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no mobile horizontal overflow');assert.ok((await atlas.boundingBox()).width<=width);await page.evaluate(()=>scrollTo(0,0));const file=`server-plan-${width}-${theme}.png`;if(output)await page.screenshot({path:path.join(output,file),fullPage:true});results.views.push({width,theme,file});}
 await atlas.locator('summary').click();assert.equal(await atlas.locator('li').count(),7);await atlas.locator('summary').click();
 const popupPromise=page.waitForEvent('popup');await atlas.getByRole('link',{name:'放大查看',exact:true}).click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert.equal(await popup.locator('#editable-labels text').count(),15);assert.equal(await popup.locator('#editable-leaders path').count(),12);const embedded=await popup.locator('svg>image').getAttribute('href');const native=fs.readFileSync(path.join(root,'web/assets/technical-atlas/server-plan-v1.png'));assert.deepEqual(Buffer.from(embedded.split(',')[1],'base64'),native);
 const positions=await popup.locator('#editable-labels text').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBBox();return{id:n.id,x:b.x,y:b.y,width:b.width,height:b.height}}));for(const b of positions){assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=1536&&b.y+b.height<=1024,'full SVG text in bounds:'+b.id);}for(let i=0;i<positions.length;i++)for(let j=i+1;j<positions.length;j++){const a=positions[i],b=positions[j];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,'no label overlap');}results.full_svg_labels=15;results.embedded_master_sha256=hash(native);results.labels=positions;
 if(output){const svg=await popup.locator('svg').evaluate(n=>n.outerHTML);const full=await browser.newPage({viewport:{width:1536,height:1024},deviceScaleFactor:1});await full.goto(base+'/server-plan.html');await full.setContent('<!doctype html><head><link rel="stylesheet" href="'+base+'/assets/fonts/fonts.css"><style>body{margin:0}svg{display:block}</style></head><body>'+svg+'</body>');await full.evaluate(()=>document.fonts.ready);await full.locator('svg').screenshot({path:path.join(output,'server-plan-full-svg.png')});await full.close();}await popup.close();
 for(const [label,file] of [['下载标注图','server-plan-v1.svg'],['下载无字底图','server-plan-v1.png']]){const pending=page.waitForEvent('download');await atlas.getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(d.suggestedFilename(),file);const bytes=fs.readFileSync(await d.path()),expected=fs.readFileSync(path.join(root,'web/assets/technical-atlas',file));assert.equal(hash(bytes),hash(expected));results.downloads.push({file,bytes:bytes.length,sha256:hash(bytes)});}
 // Browser-only fixture loads the actual module, not a production debug endpoint.
 await page.route('**/server-plan-native-check',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><script type="importmap">{"imports":{"three":"/assets/vendor/three.module.js"}}</script><canvas></canvas><script type="module">import * as THREE from"three";import{renderNativeServerPlan}from"/assets/server-plan-generator.js";window.fixture={THREE,plan:renderNativeServerPlan(document.querySelector("canvas"))};</script>'}));await page.goto(base+'/server-plan-native-check');await page.waitForFunction(()=>window.fixture);
 results.projection=await page.evaluate(()=>{const {THREE,plan}=window.fixture;const a=plan.assembly;const homes=[];a.root.traverse(o=>{if(o.userData.assemblyHome)homes.push({name:o.name,current:o.position.toArray(),home:o.userData.assemblyHome});});const ray=new THREE.Raycaster(),visible=[...a.groups.drives.children];const upper=[];for(const x of [-2.1,-.7,.7,2.1]){const p=plan.point(x,1,4.27);ray.setFromCamera(new THREE.Vector2(p[0]/1536*2-1,1-p[1]/1024*2),plan.camera);const hit=ray.intersectObjects(visible,true)[0];let o=hit.object;while(o.parent!==a.groups.drives)o=o.parent;upper.push(o.name);}return{...plan.evidence,homes,upper_drive_hits:upper,geometry_groups:Object.keys(a.groups),gpu_zone_centers:a.groups.GPU.children.map(o=>o.position.toArray()),roof_visible:a.groups.lid.visible,png:plan.png()};});
 const e=results.projection;assert.equal(e.projection,'OrthographicCamera');assert.deepEqual(e.native_pixels,[1536,1024]);assert.ok(Math.abs(e.camera_direction[0])<1e-12&&Math.abs(e.camera_direction[1]+1)<1e-12&&Math.abs(e.camera_direction[2])<1e-12);assert.equal(e.roof_visible,false);assert.deepEqual(e.counts,{server:1,cpu:2,dram:8,gpu:2,ssd:8,nic:1,psu:2,'server-fan':4});assert.equal(e.mesh_count,1129);assert.deepEqual(e.upper_drive_hits,['drive-2','drive-4','drive-6','drive-8']);assert.equal(e.homes.length,17);for(const o of e.homes)assert.deepEqual(o.current,o.home,'no moved source assembly:'+o.name);const [tl,tr,bl,br]=e.outer_corners;assert.equal(tl[1],tr[1]);assert.equal(bl[1],br[1]);assert.equal(tl[0],bl[0]);assert.equal(tr[0],br[0]);assert.ok(Math.abs((tr[0]-tl[0])-(br[0]-bl[0]))<1e-10);results.projection.rerender_sha256=hash(Buffer.from(e.png.split(',')[1],'base64'));delete e.png;assert.equal(results.projection.rerender_sha256,hash(native),'formal PNG is the direct native renderer output at source geometry');await page.evaluate(()=>{window.fixture.plan.dispose();window.fixture.plan.dispose();});
 await page.goto(base+'/bom.html#server');await page.locator('.technical-atlas[data-figure="TA-11"]').waitFor();assert.equal(await page.locator('[data-related-figure="TA-12"]').getAttribute('href'),'/server-plan.html');assert.equal(await page.locator('.technical-atlas[data-figure="TA-12"]').count(),0,'default server dossier remains TA11');await page.locator('#c-gpu').click();await page.locator('.technical-atlas[data-figure="TA-04"]').waitFor();assert.equal(await page.locator('[data-related-figure="TA-12"]').count(),0,'other parts cannot inherit server plan');assert.deepEqual(results.page_errors,[]);if(output)fs.writeFileSync(path.join(output,'server-plan-results.json'),JSON.stringify(results,null,2)+'\n');console.log('server plan passed: real orthographic/native PNG, source homes+upper-tier occlusion,4theme/size views,15editable labels/full downloads,old dossier and other part');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
