/* TA16: real system page identity/navigation and original-byte downloads.
 * Geometry/visual quality is reviewed separately; counts do not prove it.
 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright');
const root=path.join(__dirname,'..'),base=process.env.UI_BASE_URL,out=process.env.REVIEW_SCREENSHOTS,scenario=process.argv[2]||'all';
assert.ok(base,'UI_BASE_URL required');assert.ok(['all','views','downloads'].includes(scenario));
const raw=fs.readFileSync(path.join(root,'web/components/system-atlas.js'),'utf8'),items=JSON.parse(raw.slice(raw.indexOf('{'),raw.lastIndexOf('}')+1)),bom=JSON.parse(fs.readFileSync(path.join(root,'framework/bom.json'))),rights=JSON.parse(fs.readFileSync(path.join(root,'framework/site_rights.json'))).rights,physical=bom.parts.filter(p=>(p.kind||'part')==='part'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
// Element screenshots do not repaint beyond a normal viewport in every Chromium mode.
// Keep the interaction viewport, then record an explicitly taller full-element capture.
async function captureWholeFigure(page, host, file, interactionViewport) {
 await host.evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));
 await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 let box=await host.boundingBox(),height=interactionViewport.height;
 for(let attempt=0;attempt<2;attempt++) {
  const required=Math.ceil(box.y+box.height+32);
  if(required<=height)break;
  height=required;await page.setViewportSize({width:interactionViewport.width,height});
  await host.evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));box=await host.boundingBox();
 }
 assert.ok(box.y>=0&&box.y+box.height<=height,'the complete saved figure must be inside the painted capture viewport');
 await host.screenshot({path:file});
 await page.setViewportSize(interactionViewport);
 return {height,box,interaction_viewport:interactionViewport};
}
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true}),results={observed_at:new Date().toISOString(),base,scenario,page_errors:[],selections:[],views:[],downloads:[]};const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>results.page_errors.push(e.message));const firstStarted=Date.now();
 await page.goto(base+'/bom.html',{waitUntil:'domcontentloaded'});await page.locator('.equipment[data-part="ssd"]').waitFor();await page.evaluate(()=>document.fonts.ready);results.first_cards_and_fonts_ready_ms=Date.now()-firstStarted;
 assert.equal(await page.locator('.equipment').count(),61);assert.equal(await page.locator('.system-section').count(),5);assert.equal(await page.locator('.system-chain').count(),16);assert.equal(await page.locator('.system-subhead').count(),4);assert.equal(await page.locator('.system-software .pchip[data-part="dcim"]').count(),1);assert.equal(await page.locator('.system-software img,.system-software svg').count(),0);assert.equal(await page.locator('.other-entries .pchip[data-part="modular-dc"]').count(),1);assert.equal(await page.locator('.other-entries .pchip').count(),rights.length+1);assert.ok(await page.locator('#selected-atlas').evaluate(e=>e.hidden));
 assert.deepEqual((await page.locator('.equipment').evaluateAll(es=>es.map(e=>e.dataset.part))).sort(),physical.map(p=>p.id).sort());
 for(const p of physical){const image=page.locator(`.equipment[data-part="${p.id}"] img`);assert.equal(await image.count(),1);assert.ok(await image.getAttribute('alt'));assert.match(await page.locator(`.equipment[data-part="${p.id}"] .part-status`).textContent(),/^供应状态：/);}
 if(scenario!=='downloads'){
  for(const[id,item]of Object.entries(items)){await page.locator(`.equipment[data-part="${id}"]`).click();const atlas=page.locator('#selected-atlas .technical-atlas[data-figure="TA-16"]');await atlas.waitFor();await atlas.locator('img').evaluate(i=>i.decode());assert.equal(await page.locator('.technical-atlas').count(),1);assert.equal(await page.locator('#dossier .technical-atlas').count(),0);assert.equal(await atlas.locator('h3').textContent(),item.title);assert.equal(await atlas.locator('img').getAttribute('src'),item.preview);assert.equal(await atlas.locator('figcaption').textContent(),item.note);assert.equal(await atlas.locator('li').count(),item.labels.length);await atlas.locator('summary').click();assert.ok(await atlas.locator('li').first().isVisible());assert.equal(await atlas.locator('li').first().evaluate(e=>getComputedStyle(e).fontSize),'14px');await atlas.locator('summary').click();assert.ok(await page.locator('#selected-atlas').evaluate((e,id)=>e.previousElementSibling.matches(`.lrow[data-row-parts~="${id}"]`),id));assert.equal(new URL(page.url()).hash,'#'+id);assert.ok((await page.locator('#dossier').textContent()).includes(item.note),'generic example scope precedes category research');for(const width of[1280,390]){await page.setViewportSize({width,height:width===390?844:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const b=await atlas.boundingBox();assert.ok(b.width>width*.45&&b.width<=width);assert.ok(await atlas.locator('img').evaluate(i=>i.complete&&i.naturalWidth===1536&&i.naturalHeight===1024));}results.selections.push({id,title:item.title,preview:item.preview,labels:item.labels.length,scope_note:true,owned_row:true});await page.setViewportSize({width:1280,height:900});}
  for(const id of['transformer','cdu','general-server','quick-disconnect']){await page.locator(`.equipment[data-part="${id}"]`).click();const atlas=page.locator('#selected-atlas');await atlas.locator('img').evaluate(i=>i.decode());for(const width of[1280,390])for(const theme of['light','dark']){await page.setViewportSize({width,height:width===390?844:900});await page.locator('#ui-appearance').selectOption(theme);await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await atlas.locator('figure>a').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 249, 242)');let capture=null;if(out)capture=await captureWholeFigure(page,atlas,path.join(out,`system-${id}-${width}-${theme}.png`),{width,height:width===390?844:900});results.views.push({id,width,theme,capture});}const popupPending=page.waitForEvent('popup');await atlas.getByRole('link',{name:'放大查看',exact:true}).click();const popup=await popupPending;await popup.waitForLoadState('domcontentloaded');assert.equal(await popup.locator('#editable-labels .label').count(),items[id].labels.length);const encoded=await popup.locator('svg image').getAttribute('href');assert.equal(hash(Buffer.from(encoded.split(',')[1],'base64')),hash(fs.readFileSync(path.join(root,'web'+items[id].master))));if(out){await popup.setViewportSize({width:1536,height:1024});await popup.evaluate(()=>document.fonts.ready);await popup.screenshot({path:path.join(out,`system-${id}-full-svg.png`)});} (results.zoom_exports||=[]).push({id,url:popup.url(),labels:items[id].labels.length,native_sha256:hash(Buffer.from(encoded.split(',')[1],'base64'))});await popup.close();}
  await page.locator('.equipment[data-part="transformer"]').click();await page.locator('.technical-atlas[data-figure="TA-16"]').waitFor();await page.locator('[data-system-link="thermal"]').click();await page.waitForFunction(()=>location.hash==='#system-thermal'&&document.getElementById('selected-atlas').hidden);for(const mode of['scale','system']){await page.locator(`[data-mode="${mode}"]`).click();assert.ok(await page.locator('#selected-atlas').evaluate(e=>e.hidden&&e.childElementCount===0),'navigation hash cannot relocate a stale transformer figure to SSD');assert.equal(await page.locator('.sel').count(),0);assert.equal(await page.locator('#dossier').getAttribute('data-part-id'),null);}results.navigation_mode_regression={selected:'transformer',navigation:'#system-thermal',modes:['scale','system'],stale_detail_cleared:true};await page.locator('.equipment[data-part="quick-disconnect"]').click();await page.locator('.technical-atlas[data-figure="TA-16"]').waitFor();
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'关闭部件档案',exact:true}).click();assert.equal(new URL(page.url()).hash,'');assert.equal(await page.locator('.sel').count(),0);assert.ok(await page.locator('#selected-atlas').evaluate(e=>e.hidden&&e.childElementCount===0));for(const id of['facility','power','thermal','it','control']){await page.locator(`[data-system-link="${id}"]`).click();assert.equal(new URL(page.url()).hash,'#system-'+id);assert.equal(await page.locator('#system-'+id).count(),1);await page.waitForFunction(id=>{const h=document.querySelector('#system-'+id+' .sysh').getBoundingClientRect(),bar=document.querySelector('.topbar').getBoundingClientRect();return h.top>=bar.bottom&&h.bottom<=innerHeight},id);const position=await page.evaluate(id=>{const h=document.querySelector('#system-'+id+' .sysh').getBoundingClientRect(),bar=document.querySelector('.topbar').getBoundingClientRect();return{id,scroll_y:scrollY,heading:{top:h.top,bottom:h.bottom},fixed_topbar_bottom:bar.bottom,viewport_height:innerHeight}},id);(results.system_navigation_positions||=[]).push(position);}for(const id of['hdd','power-shelf']){await page.locator(`.equipment[data-part="${id}"]`).click();await page.locator('.technical-atlas[data-figure="TA-16"]').waitFor();await page.locator('[data-mode="scale"]').click();assert.ok(await page.locator('#selected-atlas').evaluate(e=>e.hidden),'system-only figure does not replace retained scale bindings');assert.equal(new URL(page.url()).search,'?view=scale');await page.locator('[data-mode="system"]').click();await page.locator('.technical-atlas[data-figure="TA-16"]').waitFor();assert.equal(new URL(page.url()).hash,'#'+id);}await page.setViewportSize({width:360,height:800});const bar=await page.locator('#ui-skinbar').boundingBox();assert.ok(bar.height<=86,'shared two-row phone bar');results.phone_bar=bar;
  await page.goto(base+'/bom.html#cdu',{waitUntil:'domcontentloaded'});await page.locator('.technical-atlas[data-figure="TA-16"]').waitFor();assert.equal(await page.locator('.technical-atlas h3').textContent(),items.cdu.title);if(out){await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'关闭部件档案',exact:true}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'system-page-390-first-screen.png')});}
 }
 if(scenario!=='views')for(const[label,url]of[['下载标注总览','/assets/technical-atlas/system-overview-v2.svg'],['下载无字总览','/assets/technical-atlas/system-overview-v2.png']]){const pending=page.waitForEvent('download');await page.locator('#system-overview-actions').getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(await d.failure(),null);const bytes=fs.readFileSync(await d.path()),expected=fs.readFileSync(path.join(root,'web'+url));assert.equal(hash(bytes),hash(expected));results.downloads.push({id:'overview',url,bytes:bytes.length,sha256:hash(bytes)});}
 if(scenario!=='views')for(const[id,item]of Object.entries(items)){await page.locator(`.equipment[data-part="${id}"]`).click();const atlas=page.locator('#selected-atlas .technical-atlas[data-figure="TA-16"]');await atlas.waitFor();for(const[label,url]of[['下载标注图',item.image],['下载无字底图',item.master]]){assert.equal(await atlas.getByRole('link',{name:label,exact:true}).getAttribute('href'),url);const pending=page.waitForEvent('download');await atlas.getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(await d.failure(),null);assert.equal(d.suggestedFilename(),path.basename(url));const bytes=fs.readFileSync(await d.path()),expected=fs.readFileSync(path.join(root,'web'+url));assert.equal(hash(bytes),hash(expected));results.downloads.push({id,url,bytes:bytes.length,sha256:hash(bytes)});}}
 if(scenario==='views'){const masters=new Set(Object.values(items).map(x=>x.master));assert.ok(!requests.some(url=>masters.has(new URL(url).pathname)),'normal system cards/details must not fetch original PNG masters');results.previews_avoid_original_master_requests=true;results.request_paths=requests.map(url=>new URL(url).pathname);}
 assert.deepEqual(results.page_errors,[]);if(out)fs.writeFileSync(path.join(out,'system-atlas-'+scenario+'-results.json'),JSON.stringify(results,null,2)+'\n');console.log('PASS TA16 '+scenario+': 61 category identities, five systems/16 physical chains/software+rights; selections='+results.selections.length+', view cases='+results.views.length+', verified downloads='+results.downloads.length);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
